In [230]:
#!pip install selenium

In [200]:
#### Import the all required Libraries
import selenium
import pandas as pd
from selenium import webdriver

In [201]:
#### conncet to the browser driver 
driver = webdriver.Chrome(r'D:\chromedriver_win32\chromedriver.exe')

In [202]:
driver

In [203]:
##### Q1

In [204]:
#### load the Url
url = 'https://www.naukri.com/'
driver.get(url)

In [205]:
### search for Job
search_job = driver.find_element_by_id('qsb-keyword-sugg')
search_job

In [206]:
##### write on search bar
search_job.send_keys('Data Analyst')

In [207]:
##### find the element for job location bar
search_location = driver.find_element_by_id('qsb-location-sugg')
search_location

In [208]:
##### write on location bar'
search_location.send_keys('Bangalore')

In [209]:
##### click on search button kby xpath as well as id/class
#search_btn = driver.find_element_by_class_name('btn')
search_btn = driver.find_element_by_xpath("//button[@class='btn']")
search_btn.click()

In [210]:
##### first 10 job  extract
title_tag = driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
title_tag

[<selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="90e9ecb7-c1ff-432a-a849-2a5968b09b85")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="cce50a7c-72bf-426d-839c-5ec3ef634959")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="9b7571da-c9ef-4230-a35e-ed81947b70a2")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="594e0958-ae30-4038-8fad-7a312f32adac")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="35ae2467-8e23-4944-960e-494e725ca4b2")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="74d7fbf9-6149-4937-97d3-857fb58027ae")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="0e34d801-f3a9-413a-bd50-7e4ae6eae316")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="f27bf6ec-2e85-485f-8fc0-ea6bb7acf002")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="5e6f64ce-7624-4045-a39c-9c78d7fdebe2")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="ead168b9-2478-47ba-8fcc-9d2baa746894")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="d2a50142-6694-4cab-aa5a-de9ea8b3c5eb")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="8786bd3c-8f45-442d-bbc8-16c517879070")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="9c48eb0d-1b8d-4bbd-99da-a2cecf0cf7ac")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="a6fc1688-3e60-42ec-81ed-827a39f46cbc")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="dd166405-a0c7-4dbf-8bb8-171716c812ec")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="67c1a8b7-7157-4221-86a9-f350e67e48ce")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="1fd2506b-7efb-493c-aacd-e7961f026759")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="127ff340-6c88-4f39-aad4-5ebee8a37610")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="ee2d2eef-f7df-42a3-b442-cea7be97e380")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="57de5fcc-1d99-4868-b20b-d4c5c81337f5")>]

In [211]:
####
job_title = []
for i in title_tag:
    job_title.append(i.text)
job_title

['Senior Data Analyst - Data Lineage',
 'Data Analyst - Informatica MDM',
 'Data analysts',
 'Excel VBA Jobs Bangalore | VBA data analyst Jobs',
 'Data Analyst (2positions)//immediate Joiners//bangalore',
 'Business/Data Analyst - SSE/LA',
 'Business Data Analyst',
 'Data Analyst',
 'Data Analyst',
 'Data Analyst - Category Demand Management (Revenue & Growth)',
 'data analyst',
 'RC HIA - Data Analyst - A2',
 'Data Analyst (Contractual)',
 'Procurement Data Analyst',
 'Data Analyst',
 'Hiring Consultant Data Analyst Contractual',
 'Data Analyst/ Data Consultant (Various Levels â€“ Senior/ Mid/ Junior)',
 'Data Scientist / Data Analyst -Business Analyst',
 'Senior Data Analyst',
 'Senior Data Analyst']

In [212]:
job_location = driver.find_elements_by_xpath('//li[@class="fleft grey-text br2 placeHolderLi location"]/span')
job_location

[<selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="5443ed4f-ba33-49b7-b938-54f14d6f5616")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="80c079e2-ff43-4f27-94f1-d5b37a822485")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="ef71ab6f-31f7-4ec9-a47a-098c037cafda")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="cc71d72c-b59f-4f36-b75e-aa0b94408106")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="e1908e56-afed-4ced-a008-7344dee06828")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="48e8284d-9a05-4c9c-ac12-9731a167eba6")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="3964bca5-981f-4429-9994-c12857bb2f5a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="7b43403b-1bdf-4a12-a8bd-d2bcc00b4cb4")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="bc3d21bd-a6f8-4a74-be8b-34b77a6bfb5a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="06bd7d1f-0bec-4f07-8bb0-03e6f9e77b11")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="21165ec8-9a4a-4e88-a733-e6b6dcf25e83")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="ceff91e8-34e6-4ad1-b480-1530ac70fe6a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="a0cc897b-3be2-4e1c-8b0f-e5430d28832b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="35517429-e96a-4a16-b0dd-7ba495bf1748")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="cc34f9bf-6c1a-48f5-9827-cd7457a028c4")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="f1ab7590-525a-42f0-af00-6c6dbfe4f11e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="97d76311-549c-4ecb-8ec1-ec19265d3e8f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="bc6247b3-767c-4f18-a9bf-758858f5cf0a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="9087b005-1b83-404d-8b4a-1791a91182a6")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="f2f00738-e333-4007-a351-60eb36ed7f66")>]

In [213]:
location_list = []
for i in job_location:
    location_list.append(i.text)
location_list

['Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Mysore/Mysuru, Coimbatore, Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Chennai, Bangalore/Bengaluru, Mumbai (All Areas)',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Pune, Chennai, Jaipur, Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru(Bellandur)',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Mumbai, Hyderabad/Secunderabad, Pune, Gurgaon/Gurugram, Chennai, Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Hyderabad/Secunderabad, Bangalore/Bengaluru']

In [214]:
company_Data = driver.find_elements_by_xpath('//a[@class="subTitle ellipsis fleft"]')
company_Data

[<selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="4d82faad-cccd-4ea0-a60f-9e4a1eaa5479")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="b5e6ca4e-157f-4e47-90b6-3a3de81d9762")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="ebe6be24-c1e6-4f74-8bb9-ddad852b5ebb")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="9f49fa2a-e86d-4113-ab93-194c516b81cb")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="29ec2259-c300-4251-a214-a495095a0bea")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="9b5ba31b-bae9-4cf3-a7cb-bd6d2fa3d770")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="dd405dc2-ea2d-4111-9d9e-8111295fe145")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="b6537b09-4d25-4a45-a7bf-10201008f385")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="dc1f0663-5229-4add-92d8-47d3fb1235ae")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="0683a710-f724-476a-96e4-37f78cb64274")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="8c8d184a-d973-45a8-91f4-06ea0c931af1")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="9a981a2c-f0e7-4f0a-8bcd-c83edf61b790")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="747336dd-4933-4ee3-a808-e57b33b82d9e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="24c9e164-c83d-4c91-ba6d-4673b875e876")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="e38eb2ce-336c-4ebc-9cc2-33cb57f0193e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="961c8dc1-3e3e-43a2-a050-1d2fefb8b411")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="eda8defe-5120-427f-892d-54cadee19f82")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="efa702db-7bb0-409c-b297-e5b770e8d93a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="30ada2fc-e9ac-43bf-983e-7cf782aa9b41")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="eccb9fa3-7b64-442e-9b23-6a8827ac2040")>]

In [215]:
company_list = []
for i in company_Data:
    company_list.append(i.text)
company_list

['Opex Global Services',
 'Shell India Markets Private Limited',
 'IBM India Pvt. Limited',
 'Mind Circus Innovation',
 'Tech Mahindra Ltd.',
 'CGI Information Systems and Management Consultants',
 'dotSolved India Pvt., Ltd.',
 'Myntra Designs Pvt. Ltd.',
 'Myntra Designs Pvt. Ltd.',
 'Myntra Designs Pvt. Ltd.',
 'Disha Consultants',
 'Pricewaterhouse Coopers Private Limited',
 'Flipkart Internet Private Limited',
 'Schneider Electric',
 'IBM India Pvt. Limited',
 'Flipkart Internet Private Limited',
 'DVSUM INDIA PRIVATE LIMITED',
 'Inflexion Analytix Private Limited',
 'Cimpress India Private Limited',
 'Eze Castle Integration Services (Formerly Alphaserve Technologies)']

In [216]:
exp_data = driver.find_elements_by_xpath('//li[@class="fleft grey-text br2 placeHolderLi experience"]/span')
exp_data

[<selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="c38b3004-5568-4fdf-ac08-55c3b07836d3")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="e2424309-c6a6-4e46-803c-4215e064f0c1")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="bcfc8f09-e938-4154-9894-a2f1f1412d98")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="f32dca7b-ed24-4918-92cd-c6f2da143e69")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="a7baf6f7-5679-43ce-91e2-3cda8b1931d8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="1bbfebb5-f6ff-486b-b11a-536abb0e72f3")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="cb9ed9f7-d30d-4751-bdc7-9709a877408d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="e594fbf9-dd15-4146-991a-57f6fc99897a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="30321923-3bcb-45e9-933b-b16508924038")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="adbc88a7-c3a8-44aa-9abd-7867364b9b09")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="12e8fcaf-5f84-45bd-a125-842005ea50b2")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="61430043-cf85-4d6d-919f-e0cd3ed2fc26")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="c900987e-d6fe-4f78-9dd5-b2a7d599f759")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="bde8d31f-c7e4-4ff6-ba0e-a53f03e599ac")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="db69198f-1b5a-4218-972e-7240e7fceb1b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="6def5e28-5ac6-48df-bab9-9bd4b6156f99")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="5f7547fe-8932-4933-910d-095e8dcc0148")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="001cf117-5b6e-4d97-b5ac-f01fe88e4b89")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="eb8dea73-bcdb-4a88-b330-ec940100fcbe")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="a077c34b-2c8b-4b34-b4da-9799bdb37d7d")>]

In [217]:
exp_list = []
for i in exp_data:
    exp_list.append(i.text)
exp_list

['5-10 Yrs',
 '6-9 Yrs',
 '3-5 Yrs',
 '0-1 Yrs',
 '4-8 Yrs',
 '2-5 Yrs',
 '9-13 Yrs',
 '3-5 Yrs',
 '3-8 Yrs',
 '1-4 Yrs',
 '2-4 Yrs',
 '4-6 Yrs',
 '1-4 Yrs',
 '1-3 Yrs',
 '5-10 Yrs',
 '2-6 Yrs',
 '5-10 Yrs',
 '0-3 Yrs',
 '3-8 Yrs',
 '6-11 Yrs']

In [218]:
dict1 = {
    'job_title':job_title,
    'location_list':location_list,
    'company_list':company_list,
    'exp_list':exp_list
}

job = pd.DataFrame({})
job['Title']=job_title
job['Location']=location_list
job['Company']=company_list
job['Experience']=exp_list

In [219]:
job.sample(10)

,Title,Location,Company,Experience
4,Data Analyst (2positions)//immediate Joiners//...,Bangalore/Bengaluru,Tech Mahindra Ltd.,4-8 Yrs
9,Data Analyst - Category Demand Management (Rev...,Bangalore/Bengaluru,Myntra Designs Pvt. Ltd.,1-4 Yrs
8,Data Analyst,Bangalore/Bengaluru,Myntra Designs Pvt. Ltd.,3-8 Yrs
16,Data Analyst/ Data Consultant (Various Levels ...,Bangalore/Bengaluru,DVSUM INDIA PRIVATE LIMITED,5-10 Yrs
17,Data Scientist / Data Analyst -Business Analyst,"Mumbai, Hyderabad/Secunderabad, Pune, Gurgaon/...",Inflexion Analytix Private Limited,0-3 Yrs
6,Business Data Analyst,"Chennai, Bangalore/Bengaluru, Mumbai (All Areas)","dotSolved India Pvt., Ltd.",9-13 Yrs
2,Data analysts,Bangalore/Bengaluru,IBM India Pvt. Limited,3-5 Yrs
12,Data Analyst (Contractual),Bangalore/Bengaluru(Bellandur),Flipkart Internet Private Limited,1-4 Yrs
18,Senior Data Analyst,Bangalore/Bengaluru,Cimpress India Private Limited,3-8 Yrs
14,Data Analyst,Bangalore/Bengaluru,IBM India Pvt. Limited,5-10 Yrs

In [220]:
#### Q2
url = 'https://www.naukri.com/'
driver.get(url)

In [221]:
search_job = driver.find_element_by_xpath('//input[@id="qsb-keyword-sugg"]')
search_job

In [222]:
search_job.send_keys('Data Scientist')

In [223]:
search_location = driver.find_element_by_xpath('//input[@id="qsb-location-sugg"]')
search_location

In [224]:
search_location.send_keys('Bangalore')

In [225]:
search_btn = driver.find_element_by_xpath('//button[@class="btn"]')
search_btn

In [226]:
search_btn.click()

In [227]:
job_title = driver.find_elements_by_xpath('//a[@class="title fw500 ellipsis"]')
job_title

[<selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="86daf87e-fd87-4c8a-a50b-9b769e544c6f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="2de31c14-56f9-4cb2-99d7-15417ba239f0")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="4c79d040-790e-4ad9-b423-85b67b955696")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="3b24cd97-1994-4605-88f1-0f71bb6530f6")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="75ed5cb3-2fe4-4fb7-9f96-182d27f049dc")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="cc20fc87-1ddc-48ca-9c8f-887d1d545a4b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="e128f151-ffc2-4604-95f8-be82de424d8b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="3f8c2a8a-3964-4dc2-89f0-f7db5858d817")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="f37a26cb-69ad-4c48-9a86-7af9ece5f2ab")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="f0849dd4-8080-4324-9c99-85536b909a2e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="bdc9a119-1c3d-44e5-9f0a-114a205f4554")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="463da953-67ba-4415-ab49-4d8615e3a81a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="e4657de5-3fde-4a4f-a81e-4f6f5e8fc4a8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="d76e7e26-1040-4b44-ba1e-e09ca5f17142")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="a49d0a55-19d9-413b-af54-2cd2200a6170")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="999e01e4-0844-49cb-8baf-aba03eec08c9")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="9ee72655-dbf7-44cb-8ab5-aa3014924a2e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="2c257eb6-6dff-4ccf-bb45-8059cd5a8f5d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="65390a74-2d71-41dc-96c2-10591c078519")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="a82954ec-fba0-403d-bc5d-6312cce075b3")>]

In [228]:
title_job = []
for i in job_title:
    title_job.append(i.text)
title_job

['Senior Data Scientist',
 'Immediate job opening - Senior Data Scientist',
 'Senior Data Scientist',
 'Lead Data Scientist',
 'Lead Data Scientist',
 'Data analytics / Data scientist intern (work from Home)',
 'Data Scientist - IBM Garage',
 'Digital Enterprise Architect (Data Scientist)',
 'Data Scientist',
 'Data Scientist',
 'Senior Data Scientist',
 'Senior Data Scientist',
 'Senior Data Scientist with Python',
 'Senior Data Scientist',
 'Sr Data Scientist',
 'Staff Data Scientist - Machine Learning, BigData',
 'Data Scientist - Machine Learning, BigData',
 'Data Scientist (Visualization)',
 'Data Scientist',
 'Manager - Data Scientist']

In [229]:
job_location = driver.find_elements_by_xpath('//li[@class="fleft grey-text br2 placeHolderLi location"]')
job_location

[<selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="bda58e02-e9ab-431c-9fa1-9c34aad38995")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="ad082c46-ca05-432f-92a3-d18a75bf9d32")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="6bd62331-4080-415b-a1d8-2adf138c38e5")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="b03e030d-87d2-442f-9c03-54e5d2413f65")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="185ecbaf-18bf-4d91-adfc-343728b77f3f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="6630f53d-a15c-43c4-af9e-0397b0d8f09a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="7cf82a13-b6dd-47fe-a8fc-59d5877b2418")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="f32374f0-60ed-4e55-99f4-b870c53571a8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="21892343-87c1-4831-9dc6-ec162bc61f52")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="130a29d3-df33-4a58-ab85-0e4fa1d61d82")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="847efe20-2815-4542-bf72-c854fdd09b20")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="d1475e86-1e3c-454f-8ead-f16a66238dd1")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="6eedb1b7-63da-43d7-a182-ac6c6e8520cb")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="955078ba-5bb8-4114-ab2e-1efade02782a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="a7ae633c-21df-47dc-9ffc-501df8ed4a06")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="2f7d00d9-e341-4a0b-a179-9846b972223e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="ce69afbc-70da-4465-bea1-724efc4071a7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="151c025d-1a06-4ca7-9dff-9527a448a944")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="6a9edb39-004d-4db3-a7ff-a39eca907218")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="5176a93f-3189-4ac6-a909-f2159bca7e0b")>]

In [230]:
location = []
for i in job_location:
    location.append(i.text)
location

['Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Mumbai, Gurgaon/Gurugram, Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Gurgaon/Gurugram, Bangalore/Bengaluru, Mumbai (All Areas)',
 'Kolkata, Bangalore/Bengaluru, Delhi / NCR',
 'Bengaluru/Bangalore',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Kolkata, Chandigarh, Hyderabad/Secunderabad, Pune, Ahmedabad, Chennai, Bangalore/Bengaluru, Delhi / NCR, Mumbai (All Areas)',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru, Mumbai (All Areas)',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Mumbai, Gurgaon/Gurugram, Bangalore/Bengaluru',
 'Bangalore/Bengaluru']

In [231]:
job_exp = driver.find_elements_by_xpath('//li[@class="fleft grey-text br2 placeHolderLi experience"]')
job_exp

[<selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="5a6d1e00-7787-475a-a4ea-acf9e6fd5a1c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="3548ee31-0b5b-4271-bec3-1dc3e8c9f051")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="165925ef-43ef-416a-8607-f6f9a0ea5092")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="014b182b-052d-4b5c-8e3f-88095cf0feac")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="1dbb9d9b-53fb-4e09-93fd-e4f920511801")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="4a77ea05-9a25-44bc-98e7-3d1652577830")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="94832338-9150-4fbd-a62b-cf8fbc1f5fc2")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="52fbae10-999e-4973-ae05-3734f21425e1")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="57284aa5-028c-4075-ae50-6c59f215b783")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="5701e606-769c-4098-9152-5cd5b134501a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="3178063e-a7df-4706-ba0a-5710d456ced2")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="3cbcd500-6d0f-44ac-b4b9-ca6b91f11055")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="5b6da960-7a8c-476e-afe3-84816b50b49d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="44dcae22-1336-48a4-b4ec-e9cfb147efda")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="e882f1cf-feb5-416f-b69b-86f36a521cf0")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="2b9e6624-4781-48f4-9851-5564a7ba876b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="7ddad380-a182-4d1d-a5c3-b6bbef670c06")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="6096b5c7-1e67-486b-afc1-b921c66036c7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="68fb8af0-4cfd-46fc-92cc-336e9d22509f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="b7e1c463-36f8-4b46-bc7c-9a0a85d45656")>]

In [232]:
exp = []
for i in job_exp:
    exp.append(i.text)
exp

['5-8 Yrs',
 '5-8 Yrs',
 '5-9 Yrs',
 '6-11 Yrs',
 '10-15 Yrs',
 '0-5 Yrs',
 '2-6 Yrs',
 '10-13 Yrs',
 '3-6 Yrs',
 '3-6 Yrs',
 '8-10 Yrs',
 '5-10 Yrs',
 '6-10 Yrs',
 '2-5 Yrs',
 '3-6 Yrs',
 '7-12 Yrs',
 '5-10 Yrs',
 '4-8 Yrs',
 '3-7 Yrs',
 '4-7 Yrs']

In [233]:
company_name = driver.find_elements_by_xpath('//a[@class="subTitle ellipsis fleft"]')
company_name

[<selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="3d7de6d9-37f0-4f41-ae00-1a604cdc4377")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="e81858f2-7536-439d-add3-f22eb2f90390")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="a264a902-6af3-4e7f-ba39-3f64c7ceb3ae")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="3b4d5c7d-1d77-43ba-9905-f3f4a96f9350")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="8ad8aa13-35d9-41e5-a7f8-8ad7a69f9bdb")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="f196001d-fd07-49b0-be81-7bccc776da47")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="d4ab6370-470e-4838-851f-0cc6e8117122")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="653aaf70-7707-4a9f-bdbe-3f738225f1b9")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="73cccc43-110c-4ad9-bc02-d6725ce7a65b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="86e480ff-37db-4741-a49b-fa27c9820493")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="44ba21fd-9119-49c0-bcc0-2f4b4f46bf42")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="e9da7300-465c-466f-805c-c1e243b498b7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="4f81663a-3328-4e31-acfc-bb357feb2031")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="4ad48686-13e0-416b-ae24-edcfba527a55")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="7a739dfc-7d8d-436f-8bdf-4c738c31235f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="a4d8a1fa-2fc2-4a22-abc9-469a2589a104")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="df998b3d-6595-4641-bd37-799df32c74e0")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="b33d61e5-3e4c-4912-a486-377080bf0dbe")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="6d3f04fe-0391-44c7-86d9-3ca2bcbd8d86")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="f36d7340-f444-4d33-870e-50ced6b86cdd")>]

In [234]:
company = []
for i in company_name:
    company.append(i.text)
company

['RedBus',
 'RedBus',
 'Fractal Analytics',
 'FICO',
 'Fractal Analytics',
 'TalkValley LLC',
 'IBM India Pvt. Limited',
 'Mphasis Limited',
 'IBM India Pvt. Limited',
 'IBM India Pvt. Limited',
 'Walmart Labs',
 'ExecBoardinAsia',
 'Next Bee Corporation',
 'Publicis Groupe',
 'intelligent industrial internet systems pvt ltd.',
 'Juniper Networks India Pvt Ltd',
 'Juniper Networks India Pvt Ltd',
 'Aruba Networks',
 'Fractal Analytics',
 'Applied Materials']

In [235]:
jobDS = pd.DataFrame({})
jobDS['Title'] = title_job
jobDS['Location'] = location
jobDS['Company'] = company
jobDS['Exp'] = exp

In [236]:
jobDS.iloc[0:10]

,Title,Location,Company,Exp
0,Senior Data Scientist,Bangalore/Bengaluru,RedBus,5-8 Yrs
1,Immediate job opening - Senior Data Scientist,Bangalore/Bengaluru,RedBus,5-8 Yrs
2,Senior Data Scientist,"Mumbai, Gurgaon/Gurugram, Bangalore/Bengaluru",Fractal Analytics,5-9 Yrs
3,Lead Data Scientist,Bangalore/Bengaluru,FICO,6-11 Yrs
4,Lead Data Scientist,"Gurgaon/Gurugram, Bangalore/Bengaluru, Mumbai ...",Fractal Analytics,10-15 Yrs
5,Data analytics / Data scientist intern (work f...,"Kolkata, Bangalore/Bengaluru, Delhi / NCR",TalkValley LLC,0-5 Yrs
6,Data Scientist - IBM Garage,Bengaluru/Bangalore,IBM India Pvt. Limited,2-6 Yrs
7,Digital Enterprise Architect (Data Scientist),Bangalore/Bengaluru,Mphasis Limited,10-13 Yrs
8,Data Scientist,Bangalore/Bengaluru,IBM India Pvt. Limited,3-6 Yrs
9,Data Scientist,Bangalore/Bengaluru,IBM India Pvt. Limited,3-6 Yrs

In [237]:
#### scrap full Job Description
get_link = driver.find_elements_by_xpath('//a[@class="title fw500 ellipsis"]')
get_link

[<selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="86daf87e-fd87-4c8a-a50b-9b769e544c6f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="2de31c14-56f9-4cb2-99d7-15417ba239f0")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="4c79d040-790e-4ad9-b423-85b67b955696")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="3b24cd97-1994-4605-88f1-0f71bb6530f6")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="75ed5cb3-2fe4-4fb7-9f96-182d27f049dc")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="cc20fc87-1ddc-48ca-9c8f-887d1d545a4b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="e128f151-ffc2-4604-95f8-be82de424d8b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="3f8c2a8a-3964-4dc2-89f0-f7db5858d817")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="f37a26cb-69ad-4c48-9a86-7af9ece5f2ab")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="f0849dd4-8080-4324-9c99-85536b909a2e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="bdc9a119-1c3d-44e5-9f0a-114a205f4554")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="463da953-67ba-4415-ab49-4d8615e3a81a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="e4657de5-3fde-4a4f-a81e-4f6f5e8fc4a8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="d76e7e26-1040-4b44-ba1e-e09ca5f17142")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="a49d0a55-19d9-413b-af54-2cd2200a6170")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="999e01e4-0844-49cb-8baf-aba03eec08c9")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="9ee72655-dbf7-44cb-8ab5-aa3014924a2e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="2c257eb6-6dff-4ccf-bb45-8059cd5a8f5d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="65390a74-2d71-41dc-96c2-10591c078519")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="a82954ec-fba0-403d-bc5d-6312cce075b3")>]

In [238]:
link = []
for i in get_link:
    link.append(i.get_attribute('href'))
link

['https://www.naukri.com/job-listings-senior-data-scientist-redbus-in-ibibo-group-private-limited-bangalore-bengaluru-5-to-8-years-090621001584?src=jobsearchDesk&sid=16239429601013578&xp=1&px=1',
 'https://www.naukri.com/job-listings-immediate-opening-senior-data-scientist-redbus-in-ibibo-group-private-limited-bangalore-bengaluru-5-to-8-years-140621005528?src=jobsearchDesk&sid=16239429601013578&xp=2&px=1',
 'https://www.naukri.com/job-listings-senior-data-scientist-fractal-analytics-ltd-mumbai-gurgaon-gurugram-bangalore-bengaluru-5-to-9-years-140621500966?src=jobsearchDesk&sid=16239429601013578&xp=3&px=1',
 'https://www.naukri.com/job-listings-lead-data-scientist-fico-bangalore-bengaluru-6-to-11-years-090621500701?src=jobsearchDesk&sid=16239429601013578&xp=4&px=1',
 'https://www.naukri.com/job-listings-lead-data-scientist-fractal-analytics-pvt-ltd-gurgaon-gurugram-bangalore-bengaluru-mumbai-all-areas-10-to-15-years-110621003012?src=jobsearchDesk&sid=16239429601013578&xp=5&px=1',
 'https://www.naukri.com/job-listings-data-analytics-data-scientist-intern-work-from-home-talkvalley-llc-kolkata-bangalore-bengaluru-delhi-ncr-0-to-5-years-050621000128?src=jobsearchDesk&sid=16239429601013578&xp=6&px=1',
 'https://www.naukri.com/job-listings-data-scientist-ibm-garage-ibm-india-pvt-limited-bengaluru-bangalore-2-to-6-years-080621904251?src=jobsearchDesk&sid=16239429601013578&xp=7&px=1',
 'https://www.naukri.com/job-listings-digital-enterprise-architect-data-scientist-mphasis-limited-bangalore-bengaluru-10-to-13-years-030621902728?src=jobsearchDesk&sid=16239429601013578&xp=8&px=1',
 'https://www.naukri.com/job-listings-data-scientist-ibm-india-pvt-limited-bangalore-bengaluru-3-to-6-years-020621905994?src=jobsearchDesk&sid=16239429601013578&xp=9&px=1',
 'https://www.naukri.com/job-listings-data-scientist-ibm-india-pvt-limited-bangalore-bengaluru-3-to-6-years-030621907010?src=jobsearchDesk&sid=16239429601013578&xp=10&px=1',
 'https://www.naukri.com/job-listings-senior-data-scientist-walmart-labs-bangalore-bengaluru-8-to-10-years-020621500403?src=jobsearchDesk&sid=16239429601013578&xp=11&px=1',
 'https://www.naukri.com/job-listings-senior-data-scientist-execboardinasia-bangalore-bengaluru-5-to-10-years-030621500359?src=jobsearchDesk&sid=16239429601013578&xp=12&px=1',
 'https://www.naukri.com/job-listings-senior-data-scientist-with-python-next-bee-corporation-kolkata-chandigarh-hyderabad-secunderabad-pune-ahmedabad-chennai-bangalore-bengaluru-delhi-ncr-mumbai-all-areas-6-to-10-years-140621002374?src=jobsearchDesk&sid=16239429601013578&xp=13&px=1',
 'https://www.naukri.com/job-listings-senior-data-scientist-publicis-groupe-bangalore-bengaluru-2-to-5-years-140621501233?src=jobsearchDesk&sid=16239429601013578&xp=14&px=1',
 'https://www.naukri.com/job-listings-sr-data-scientist-intelligent-industrial-internet-systems-pvt-ltd-bangalore-bengaluru-mumbai-all-areas-3-to-6-years-030621003155?src=jobsearchDesk&sid=16239429601013578&xp=15&px=1',
 'https://www.naukri.com/job-listings-staff-data-scientist-machine-learning-bigdata-juniper-networks-india-pvt-ltd-bangalore-bengaluru-7-to-12-years-150621500474?src=jobsearchDesk&sid=16239429601013578&xp=16&px=1',
 'https://www.naukri.com/job-listings-data-scientist-machine-learning-bigdata-juniper-networks-india-pvt-ltd-bangalore-bengaluru-5-to-10-years-150621500351?src=jobsearchDesk&sid=16239429601013578&xp=17&px=1',
 'https://www.naukri.com/job-listings-data-scientist-visualization-aruba-networks-bangalore-bengaluru-4-to-8-years-090621501101?src=jobsearchDesk&sid=16239429601013578&xp=18&px=1',
 'https://www.naukri.com/job-listings-data-scientist-fractal-analytics-ltd-mumbai-gurgaon-gurugram-bangalore-bengaluru-3-to-7-years-070621501457?src=jobsearchDesk&sid=16239429601013578&xp=19&px=1',
 'https://www.naukri.com/job-listings-manager-data-scientist-applied-materials-india-private-limited-bangalore-bengaluru-4-to-7-years-160621900835?src=jobsearchDesk&sid=16239429601013578&xp=20&px=1']

In [239]:
job_title = []
for i in link:
    driver.get(i)
    title = driver.find_elements_by_xpath("//h1[@class='jd-header-title']")
    for j in title:
        job_title.append(j.text)
job_title

['Senior Data Scientist',
 'Lead Data Scientist',
 'Lead Data Scientist',
 'Data analytics / Data scientist intern (work from Home)',
 'Senior Data Scientist',
 'Senior Data Scientist',
 'Senior Data Scientist with Python',
 'Senior Data Scientist',
 'Sr Data Scientist',
 'Staff Data Scientist - Machine Learning, BigData',
 'Data Scientist - Machine Learning, BigData',
 'Data Scientist (Visualization)',
 'Data Scientist']

In [240]:
company_name = []
for i in link:
    driver.get(i)
    title = driver.find_elements_by_xpath("//a[@class='pad-rt-8']")
    for j in title:
        if j.text == "":
            continue
        else:
            
            company_name.append(j.text)
company_name

['Fractal Analytics',
 'FICO',
 'Fractal Analytics',
 'TalkValley LLC',
 'Walmart Labs',
 'ExecBoardinAsia',
 'Next Bee Corporation',
 'Publicis Groupe',
 'intelligent industrial internet systems pvt ltd.',
 'Juniper Networks India Pvt Ltd',
 'Juniper Networks India Pvt Ltd',
 'Aruba Networks',
 'Fractal Analytics']

In [243]:
job_desc = []
for i in link:
    title = driver.find_elements_by_xpath("//div[@class='clearboth description']/p")
    for j in title:
        job_desc.append(j.text)
job_desc

['Technical Skills and Experience',
 'Other Skills',
 'Functional Knowledge',
 'Business Expertise',
 'Leadership',
 'Problem Solving',
 'Impact',
 'Interpersonal Skills',
 "Qualifications\nEducation: Bachelor's Degree",
 'Years of Experience: 4 - 7 Years',
 'Additional Information\nTravel:Yes, 20% of the Time',
 'Relocation Eligible:Yes',
 'Technical Skills and Experience',
 'Other Skills',
 'Functional Knowledge',
 'Business Expertise',
 'Leadership',
 'Problem Solving',
 'Impact',
 'Interpersonal Skills',
 "Qualifications\nEducation: Bachelor's Degree",
 'Years of Experience: 4 - 7 Years',
 'Additional Information\nTravel:Yes, 20% of the Time',
 'Relocation Eligible:Yes',
 'Technical Skills and Experience',
 'Other Skills',
 'Functional Knowledge',
 'Business Expertise',
 'Leadership',
 'Problem Solving',
 'Impact',
 'Interpersonal Skills',
 "Qualifications\nEducation: Bachelor's Degree",
 'Years of Experience: 4 - 7 Years',
 'Additional Information\nTravel:Yes, 20% of the Time',
 'Relocation Eligible:Yes',
 'Technical Skills and Experience',
 'Other Skills',
 'Functional Knowledge',
 'Business Expertise',
 'Leadership',
 'Problem Solving',
 'Impact',
 'Interpersonal Skills',
 "Qualifications\nEducation: Bachelor's Degree",
 'Years of Experience: 4 - 7 Years',
 'Additional Information\nTravel:Yes, 20% of the Time',
 'Relocation Eligible:Yes',
 'Technical Skills and Experience',
 'Other Skills',
 'Functional Knowledge',
 'Business Expertise',
 'Leadership',
 'Problem Solving',
 'Impact',
 'Interpersonal Skills',
 "Qualifications\nEducation: Bachelor's Degree",
 'Years of Experience: 4 - 7 Years',
 'Additional Information\nTravel:Yes, 20% of the Time',
 'Relocation Eligible:Yes',
 'Technical Skills and Experience',
 'Other Skills',
 'Functional Knowledge',
 'Business Expertise',
 'Leadership',
 'Problem Solving',
 'Impact',
 'Interpersonal Skills',
 "Qualifications\nEducation: Bachelor's Degree",
 'Years of Experience: 4 - 7 Years',
 'Additional Information\nTravel:Yes, 20% of the Time',
 'Relocation Eligible:Yes',
 'Technical Skills and Experience',
 'Other Skills',
 'Functional Knowledge',
 'Business Expertise',
 'Leadership',
 'Problem Solving',
 'Impact',
 'Interpersonal Skills',
 "Qualifications\nEducation: Bachelor's Degree",
 'Years of Experience: 4 - 7 Years',
 'Additional Information\nTravel:Yes, 20% of the Time',
 'Relocation Eligible:Yes',
 'Technical Skills and Experience',
 'Other Skills',
 'Functional Knowledge',
 'Business Expertise',
 'Leadership',
 'Problem Solving',
 'Impact',
 'Interpersonal Skills',
 "Qualifications\nEducation: Bachelor's Degree",
 'Years of Experience: 4 - 7 Years',
 'Additional Information\nTravel:Yes, 20% of the Time',
 'Relocation Eligible:Yes',
 'Technical Skills and Experience',
 'Other Skills',
 'Functional Knowledge',
 'Business Expertise',
 'Leadership',
 'Problem Solving',
 'Impact',
 'Interpersonal Skills',
 "Qualifications\nEducation: Bachelor's Degree",
 'Years of Experience: 4 - 7 Years',
 'Additional Information\nTravel:Yes, 20% of the Time',
 'Relocation Eligible:Yes',
 'Technical Skills and Experience',
 'Other Skills',
 'Functional Knowledge',
 'Business Expertise',
 'Leadership',
 'Problem Solving',
 'Impact',
 'Interpersonal Skills',
 "Qualifications\nEducation: Bachelor's Degree",
 'Years of Experience: 4 - 7 Years',
 'Additional Information\nTravel:Yes, 20% of the Time',
 'Relocation Eligible:Yes',
 'Technical Skills and Experience',
 'Other Skills',
 'Functional Knowledge',
 'Business Expertise',
 'Leadership',
 'Problem Solving',
 'Impact',
 'Interpersonal Skills',
 "Qualifications\nEducation: Bachelor's Degree",
 'Years of Experience: 4 - 7 Years',
 'Additional Information\nTravel:Yes, 20% of the Time',
 'Relocation Eligible:Yes',
 'Technical Skills and Experience',
 'Other Skills',
 'Functional Knowledge',
 'Business Expertise',
 'Leadership',
 'Problem Solving',
 'Impact',
 'Interpersonal Skills',
 "Qualifications\nEducation: Bachelor's Degree",
 'Years of Experience: 4 - 7 Years',
 'Additional Information\nTravel:Yes, 20% of the Time',
 'Relocation Eligible:Yes',
 'Technical Skills and Experience',
 'Other Skills',
 'Functional Knowledge',
 'Business Expertise',
 'Leadership',
 'Problem Solving',
 'Impact',
 'Interpersonal Skills',
 "Qualifications\nEducation: Bachelor's Degree",
 'Years of Experience: 4 - 7 Years',
 'Additional Information\nTravel:Yes, 20% of the Time',
 'Relocation Eligible:Yes',
 'Technical Skills and Experience',
 'Other Skills',
 'Functional Knowledge',
 'Business Expertise',
 'Leadership',
 'Problem Solving',
 'Impact',
 'Interpersonal Skills',
 "Qualifications\nEducation: Bachelor's Degree",
 'Years of Experience: 4 - 7 Years',
 'Additional Information\nTravel:Yes, 20% of the Time',
 'Relocation Eligible:Yes',
 'Technical Skills and Experience',
 'Other Skills',
 'Functional Knowledge',
 'Business Expertise',
 'Leadership',
 'Problem Solving',
 'Impact',
 'Interpersonal Skills',
 "Qualifications\nEducation: Bachelor's Degree",
 'Years of Experience: 4 - 7 Years',
 'Additional Information\nTravel:Yes, 20% of the Time',
 'Relocation Eligible:Yes',
 'Technical Skills and Experience',
 'Other Skills',
 'Functional Knowledge',
 'Business Expertise',
 'Leadership',
 'Problem Solving',
 'Impact',
 'Interpersonal Skills',
 "Qualifications\nEducation: Bachelor's Degree",
 'Years of Experience: 4 - 7 Years',
 'Additional Information\nTravel:Yes, 20% of the Time',
 'Relocation Eligible:Yes',
 'Technical Skills and Experience',
 'Other Skills',
 'Functional Knowledge',
 'Business Expertise',
 'Leadership',
 'Problem Solving',
 'Impact',
 'Interpersonal Skills',
 "Qualifications\nEducation: Bachelor's Degree",
 'Years of Experience: 4 - 7 Years',
 'Additional Information\nTravel:Yes, 20% of the Time',
 'Relocation Eligible:Yes',
 'Technical Skills and Experience',
 'Other Skills',
 'Functional Knowledge',
 'Business Expertise',
 'Leadership',
 'Problem Solving',
 'Impact',
 'Interpersonal Skills',
 "Qualifications\nEducation: Bachelor's Degree",
 'Years of Experience: 4 - 7 Years',
 'Additional Information\nTravel:Yes, 20% of the Time',
 'Relocation Eligible:Yes',
 'Technical Skills and Experience',
 'Other Skills',
 'Functional Knowledge',
 'Business Expertise',
 'Leadership',
 'Problem Solving',
 'Impact',
 'Interpersonal Skills',
 "Qualifications\nEducation: Bachelor's Degree",
 'Years of Experience: 4 - 7 Years',
 'Additional Information\nTravel:Yes, 20% of the Time',
 'Relocation Eligible:Yes',
 'Technical Skills and Experience',
 'Other Skills',
 'Functional Knowledge',
 'Business Expertise',
 'Leadership',
 'Problem Solving',
 'Impact',
 'Interpersonal Skills',
 "Qualifications\nEducation: Bachelor's Degree",
 'Years of Experience: 4 - 7 Years',
 'Additional Information\nTravel:Yes, 20% of the Time',
 'Relocation Eligible:Yes']

In [247]:
job_desc = pd.DataFrame(job_desc).iloc[0:13]
job_desc

                                                    0
0                     Technical Skills and Experience
1                                        Other Skills
2                                Functional Knowledge
3                                  Business Expertise
4                                          Leadership
5                                     Problem Solving
6                                              Impact
7                                Interpersonal Skills
8        Qualifications\nEducation: Bachelor's Degree
9                    Years of Experience: 4 - 7 Years
10  Additional Information\nTravel:Yes, 20% of the...
11                            Relocation Eligible:Yes
12                    Technical Skills and Experience

In [248]:
job_details =pd.DataFrame({})
job_details['Title'] = job_title
job_details['Company']=company_name
job_details['Desc']=job_desc
job_details

,Title,Company,Desc
0,Senior Data Scientist,Fractal Analytics,Technical Skills and Experience
1,Lead Data Scientist,FICO,Other Skills
2,Lead Data Scientist,Fractal Analytics,Functional Knowledge
3,Data analytics / Data scientist intern (work f...,TalkValley LLC,Business Expertise
4,Senior Data Scientist,Walmart Labs,Leadership
5,Senior Data Scientist,ExecBoardinAsia,Problem Solving
6,Senior Data Scientist with Python,Next Bee Corporation,Impact
7,Senior Data Scientist,Publicis Groupe,Interpersonal Skills
8,Sr Data Scientist,intelligent industrial internet systems pvt ltd.,Qualifications\nEducation: Bachelor's Degree
9,"Staff Data Scientist - Machine Learning, BigData",Juniper Networks India Pvt Ltd,Years of Experience: 4 - 7 Years
10,"Data Scientist - Machine Learning, BigData",Juniper Networks India Pvt Ltd,"Additional Information\nTravel:Yes, 20% of the..."
11,Data Scientist (Visualization),Aruba Networks,Relocation Eligible:Yes
12,Data Scientist,Fractal Analytics,Technical Skills and Experience

In [249]:
### Q3

url = 'https://www.naukri.com/'
driver.get(url)

In [250]:
jobs_desc = driver.find_element_by_xpath("//input[@id='qsb-keyword-sugg']")

In [251]:
jobs_desc.send_keys('Data Scientist')

In [252]:
search = driver.find_element_by_xpath('//button[@class="btn"]')
search.click()

In [253]:
filter_loc = driver.find_element_by_xpath('/html/body/div[1]/div[3]/div[2]/section[1]/div[2]/div[2]/div[2]/div[2]/label/p/span[1]').click()

In [254]:
filter_salary = driver.find_element_by_xpath('/html/body/div[1]/div[3]/div[2]/section[1]/div[2]/div[3]/div[2]/div[2]/label/p/span[1]').click()

In [255]:
job_details = driver.find_elements_by_xpath('//a[@class="title fw500 ellipsis"]')
job_details

[<selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="0ece3b30-cf35-4ae7-a5bc-4075e656b7e6")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="63867d9d-b151-4b5d-b77c-de27e7242423")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="052c8b26-e9ef-477e-a12e-73649dd6d46f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="4836199e-655d-4b12-96f6-cf12d7d2bf83")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="8229c5ba-14e4-4bf6-af34-ada85c5e4d75")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="73ba2ba0-7e0a-4dbf-95b6-aa2e94faa84c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="9d0d687e-d82e-4c2b-bd07-a0b267a86965")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="f0934b43-c0ee-4ced-aff1-fb7d4027fc91")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="4605df1c-d29b-431d-a8db-4ca787c0d022")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="6f813dda-4b8e-4d28-8665-dc6ccbc4fad1")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="51cc4e8d-da3d-4f90-bb89-9d55da533296")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="bd56f2c6-1ec9-4fa0-8838-230df6d58a8e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="4720bb53-35e2-41f3-a605-623e39ba5d70")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="46589ea6-cc99-490d-bfa3-875fd1f9f396")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="8dc46fd5-4da2-4d6d-bae0-b48c1a4f54a7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="6b783e69-4157-4fc9-9211-c515d7bf9743")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="6a7ffa89-9ed6-4629-99eb-4d4bf9c0bb74")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="7902523a-4d8a-4288-8a00-05940a89665c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="0fe4f346-fc81-41ce-8ff6-a5018bed9271")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="7642c5df-487d-4eaa-a36f-6182342360b8")>]

In [256]:
jobs = []
for i in job_details:
    jobs.append(i.text)
jobs

['Data analytics / Data scientist intern (work from Home)',
 'Chaayos is Looking For Data Scientist',
 'Data Scientist',
 'Data Scientist / Data Analyst -Business Analyst',
 'Junior Data Scientist',
 'We are hiring- Data Scientist +Python- Noida',
 'Data Scientist',
 'Data Scientist',
 'Data Analyst/Scientist Big Data, Statistical Techniques',
 'Business Analyst- Data Scientist',
 'Data Scientist',
 'Senior Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Data Scientist',
 'Associate Data Scientist',
 'Associate Data Scientist',
 'Data Scientist Machine Learning',
 'Data Scientist - Python/ SQL']

In [257]:
pd.DataFrame(jobs).iloc[0:11]

                                                    0
0   Data analytics / Data scientist intern (work f...
1               Chaayos is Looking For Data Scientist
2                                      Data Scientist
3     Data Scientist / Data Analyst -Business Analyst
4                               Junior Data Scientist
5        We are hiring- Data Scientist +Python- Noida
6                                      Data Scientist
7                                      Data Scientist
8   Data Analyst/Scientist Big Data, Statistical T...
9                    Business Analyst- Data Scientist
10                                     Data Scientist

In [258]:
##Q6
url = 'https://www.flipkart.com/'
driver.get(url)

In [259]:
search = driver.find_element_by_xpath('//input[@class="_3704LK"]')
search.send_keys('sunglasses')

In [262]:
search_btn = driver.find_element_by_xpath('//button[@class="L0Z3Pu"]').click()

In [263]:
brands = []
for i in range (0,5):
    brand = driver.find_elements_by_xpath('//div[@class="_2WkVRV"]')
    for j in brand:
        brands.append(j.text)
next_btn = driver.find_element_by_xpath('//a[@class="_1LKTO3"]')
next_btn.click()

In [264]:
brands

['PIRASO',
 'Fastrack',
 'Fastrack',
 'kingsunglasses',
 'PIRASO',
 'Fastrack',
 'PIRASO',
 'PIRASO',
 'PIRASO',
 'DEIXELS',
 'GANSTA',
 'Fastrack',
 'ROZZETTA CRAFT',
 'Singco',
 'elegante',
 'NuVew',
 'ROZZETTA CRAFT',
 'Silver Kartz',
 'PHENOMENAL',
 'HIPPON',
 'PHENOMENAL',
 'Singco India',
 'ROYAL SON',
 'ROYAL SON',
 'Singco India',
 'ROZZETTA CRAFT',
 'Singco India',
 'NuVew',
 'ROYAL SON',
 'Fastrack',
 'Singco India',
 'hipe',
 'ROZZETTA CRAFT',
 'Fravy',
 'NuVew',
 'GANSTA',
 'ROYAL SON',
 'PHENOMENAL',
 'ROZZETTA CRAFT',
 'Cristiano Ronnie',
 'PIRASO',
 'Fastrack',
 'Fastrack',
 'kingsunglasses',
 'PIRASO',
 'Fastrack',
 'PIRASO',
 'PIRASO',
 'PIRASO',
 'DEIXELS',
 'GANSTA',
 'Fastrack',
 'ROZZETTA CRAFT',
 'Singco',
 'elegante',
 'NuVew',
 'ROZZETTA CRAFT',
 'Silver Kartz',
 'PHENOMENAL',
 'HIPPON',
 'PHENOMENAL',
 'Singco India',
 'ROYAL SON',
 'ROYAL SON',
 'Singco India',
 'ROZZETTA CRAFT',
 'Singco India',
 'NuVew',
 'ROYAL SON',
 'Fastrack',
 'Singco India',
 'hipe',
 'ROZZETTA CRAFT',
 'Fravy',
 'NuVew',
 'GANSTA',
 'ROYAL SON',
 'PHENOMENAL',
 'ROZZETTA CRAFT',
 'Cristiano Ronnie',
 'PIRASO',
 'Fastrack',
 'Fastrack',
 'kingsunglasses',
 'PIRASO',
 'Fastrack',
 'PIRASO',
 'PIRASO',
 'PIRASO',
 'DEIXELS',
 'GANSTA',
 'Fastrack',
 'ROZZETTA CRAFT',
 'Singco',
 'elegante',
 'NuVew',
 'ROZZETTA CRAFT',
 'Silver Kartz',
 'PHENOMENAL',
 'HIPPON',
 'PHENOMENAL',
 'Singco India',
 'ROYAL SON',
 'ROYAL SON',
 'Singco India',
 'ROZZETTA CRAFT',
 'Singco India',
 'NuVew',
 'ROYAL SON',
 'Fastrack',
 'Singco India',
 'hipe',
 'ROZZETTA CRAFT',
 'Fravy',
 'NuVew',
 'GANSTA',
 'ROYAL SON',
 'PHENOMENAL',
 'ROZZETTA CRAFT',
 'Cristiano Ronnie',
 'PIRASO',
 'Fastrack',
 'Fastrack',
 'kingsunglasses',
 'PIRASO',
 'Fastrack',
 'PIRASO',
 'PIRASO',
 'PIRASO',
 'DEIXELS',
 'GANSTA',
 'Fastrack',
 'ROZZETTA CRAFT',
 'Singco',
 'elegante',
 'NuVew',
 'ROZZETTA CRAFT',
 'Silver Kartz',
 'PHENOMENAL',
 'HIPPON',
 'PHENOMENAL',
 'Singco India',
 'ROYAL SON',
 'ROYAL SON',
 'Singco India',
 'ROZZETTA CRAFT',
 'Singco India',
 'NuVew',
 'ROYAL SON',
 'Fastrack',
 'Singco India',
 'hipe',
 'ROZZETTA CRAFT',
 'Fravy',
 'NuVew',
 'GANSTA',
 'ROYAL SON',
 'PHENOMENAL',
 'ROZZETTA CRAFT',
 'Cristiano Ronnie',
 'PIRASO',
 'Fastrack',
 'Fastrack',
 'kingsunglasses',
 'PIRASO',
 'Fastrack',
 'PIRASO',
 'PIRASO',
 'PIRASO',
 'DEIXELS',
 'GANSTA',
 'Fastrack',
 'ROZZETTA CRAFT',
 'Singco',
 'elegante',
 'NuVew',
 'ROZZETTA CRAFT',
 'Silver Kartz',
 'PHENOMENAL',
 'HIPPON',
 'PHENOMENAL',
 'Singco India',
 'ROYAL SON',
 'ROYAL SON',
 'Singco India',
 'ROZZETTA CRAFT',
 'Singco India',
 'NuVew',
 'ROYAL SON',
 'Fastrack',
 'Singco India',
 'hipe',
 'ROZZETTA CRAFT',
 'Fravy',
 'NuVew',
 'GANSTA',
 'ROYAL SON',
 'PHENOMENAL',
 'ROZZETTA CRAFT',
 'Cristiano Ronnie']

In [265]:
pro_desc = []
for i in range (0,5):
    desc = driver.find_elements_by_xpath('//a[@class="IRpwTa"]')
    for j in desc:
        pro_desc.append(j.text)
next_btn = driver.find_element_by_xpath('//a[@class="_1LKTO3"]')
next_btn.click()

In [266]:
pro_desc

['UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'Gradient, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection, Mirrored Retro Square Sunglasses (53)',
 'UV Protection Wrap-around Sunglasses (Free Size)',
 'UV Protection Butterfly Sunglasses (65)',
 'UV Protection, Riding Glasses Aviator Sunglasses (57)',
 'UV Protection, Gradient Round Sunglasses (Free Size)',
 'Polarized, UV Protection, Riding Glasses Wayfarer Sungl...',
 'UV Protection, Gradient Round Sunglasses (Free Size)',
 'Gradient, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Round Sunglasses (Free Size)',
 'UV Protection Retro Square Sunglasses (Free Size)',
 'UV Protection, Riding Glasses Wayfarer Sunglasses (53)',
 'UV Protection, Gradient Retro Square Sunglasses (Free S...',
 'UV Protection Sports Sunglasses (Free Size)',
 'Mirrored Wayfarer Sunglasses (55)',
 'UV Protection Oval Sunglasses (60)',
 'UV Protection, Night Vision, Riding Glasses Aviator Sun...',
 'UV Protection Round Sunglasses (Free Size)',
 'UV Protection, Riding Glasses Wayfarer Sunglasses (56)',
 'UV Protection, Mirrored Clubmaster Sunglasses (Free Siz...',
 'UV Protection, Riding Glasses Aviator Sunglasses (58)',
 'UV Protection Retro Square Sunglasses (Free Size)',
 'UV Protection, Mirrored Sports Sunglasses (73)',
 'UV Protection Shield Sunglasses (Free Size)',
 'UV Protection, Gradient Butterfly, Retro Square Sunglas...',
 'UV Protection, Riding Glasses Aviator Sunglasses (58)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Retro Square Sunglasses (58)',
 'UV Protection, Mirrored Retro Square Sunglasses (Free S...',
 'Mirrored, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Aviator Sunglasses (54)',
 'Mirrored, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection, Polarized Rectangular Sunglasses (Free S...',
 'Mirrored Round Sunglasses (51)',
 'UV Protection, Mirrored Aviator Sunglasses (Free Size)',
 'Gradient, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Wayfarer Sunglasses (56)',
 'UV Protection Round Sunglasses (Free Size)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'Gradient, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection, Mirrored Retro Square Sunglasses (53)',
 'UV Protection Wrap-around Sunglasses (Free Size)',
 'UV Protection Butterfly Sunglasses (65)',
 'UV Protection, Riding Glasses Aviator Sunglasses (57)',
 'UV Protection, Gradient Round Sunglasses (Free Size)',
 'Polarized, UV Protection, Riding Glasses Wayfarer Sungl...',
 'UV Protection, Gradient Round Sunglasses (Free Size)',
 'Gradient, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Round Sunglasses (Free Size)',
 'UV Protection Retro Square Sunglasses (Free Size)',
 'UV Protection, Riding Glasses Wayfarer Sunglasses (53)',
 'UV Protection, Gradient Retro Square Sunglasses (Free S...',
 'UV Protection Sports Sunglasses (Free Size)',
 'Mirrored Wayfarer Sunglasses (55)',
 'UV Protection Oval Sunglasses (60)',
 'UV Protection, Night Vision, Riding Glasses Aviator Sun...',
 'UV Protection Round Sunglasses (Free Size)',
 'UV Protection, Riding Glasses Wayfarer Sunglasses (56)',
 'UV Protection, Mirrored Clubmaster Sunglasses (Free Siz...',
 'UV Protection, Riding Glasses Aviator Sunglasses (58)',
 'UV Protection Retro Square Sunglasses (Free Size)',
 'UV Protection, Mirrored Sports Sunglasses (73)',
 'UV Protection Shield Sunglasses (Free Size)',
 'UV Protection, Gradient Butterfly, Retro Square Sunglas...',
 'UV Protection, Riding Glasses Aviator Sunglasses (58)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Retro Square Sunglasses (58)',
 'UV Protection, Mirrored Retro Square Sunglasses (Free S...',
 'Mirrored, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Aviator Sunglasses (54)',
 'Mirrored, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection, Polarized Rectangular Sunglasses (Free S...',
 'Mirrored Round Sunglasses (51)',
 'UV Protection, Mirrored Aviator Sunglasses (Free Size)',
 'Gradient, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Wayfarer Sunglasses (56)',
 'UV Protection Round Sunglasses (Free Size)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'Gradient, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection, Mirrored Retro Square Sunglasses (53)',
 'UV Protection Wrap-around Sunglasses (Free Size)',
 'UV Protection Butterfly Sunglasses (65)',
 'UV Protection, Riding Glasses Aviator Sunglasses (57)',
 'UV Protection, Gradient Round Sunglasses (Free Size)',
 'Polarized, UV Protection, Riding Glasses Wayfarer Sungl...',
 'UV Protection, Gradient Round Sunglasses (Free Size)',
 'Gradient, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Round Sunglasses (Free Size)',
 'UV Protection Retro Square Sunglasses (Free Size)',
 'UV Protection, Riding Glasses Wayfarer Sunglasses (53)',
 'UV Protection, Gradient Retro Square Sunglasses (Free S...',
 'UV Protection Sports Sunglasses (Free Size)',
 'Mirrored Wayfarer Sunglasses (55)',
 'UV Protection Oval Sunglasses (60)',
 'UV Protection, Night Vision, Riding Glasses Aviator Sun...',
 'UV Protection Round Sunglasses (Free Size)',
 'UV Protection, Riding Glasses Wayfarer Sunglasses (56)',
 'UV Protection, Mirrored Clubmaster Sunglasses (Free Siz...',
 'UV Protection, Riding Glasses Aviator Sunglasses (58)',
 'UV Protection Retro Square Sunglasses (Free Size)',
 'UV Protection, Mirrored Sports Sunglasses (73)',
 'UV Protection Shield Sunglasses (Free Size)',
 'UV Protection, Gradient Butterfly, Retro Square Sunglas...',
 'UV Protection, Riding Glasses Aviator Sunglasses (58)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Retro Square Sunglasses (58)',
 'UV Protection, Mirrored Retro Square Sunglasses (Free S...',
 'Mirrored, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Aviator Sunglasses (54)',
 'Mirrored, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection, Polarized Rectangular Sunglasses (Free S...',
 'Mirrored Round Sunglasses (51)',
 'UV Protection, Mirrored Aviator Sunglasses (Free Size)',
 'Gradient, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Wayfarer Sunglasses (56)',
 'UV Protection Round Sunglasses (Free Size)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'Gradient, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection, Mirrored Retro Square Sunglasses (53)',
 'UV Protection Wrap-around Sunglasses (Free Size)',
 'UV Protection Butterfly Sunglasses (65)',
 'UV Protection, Riding Glasses Aviator Sunglasses (57)',
 'UV Protection, Gradient Round Sunglasses (Free Size)',
 'Polarized, UV Protection, Riding Glasses Wayfarer Sungl...',
 'UV Protection, Gradient Round Sunglasses (Free Size)',
 'Gradient, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Round Sunglasses (Free Size)',
 'UV Protection Retro Square Sunglasses (Free Size)',
 'UV Protection, Riding Glasses Wayfarer Sunglasses (53)',
 'UV Protection, Gradient Retro Square Sunglasses (Free S...',
 'UV Protection Sports Sunglasses (Free Size)',
 'Mirrored Wayfarer Sunglasses (55)',
 'UV Protection Oval Sunglasses (60)',
 'UV Protection, Night Vision, Riding Glasses Aviator Sun...',
 'UV Protection Round Sunglasses (Free Size)',
 'UV Protection, Riding Glasses Wayfarer Sunglasses (56)',
 'UV Protection, Mirrored Clubmaster Sunglasses (Free Siz...',
 'UV Protection, Riding Glasses Aviator Sunglasses (58)',
 'UV Protection Retro Square Sunglasses (Free Size)',
 'UV Protection, Mirrored Sports Sunglasses (73)',
 'UV Protection Shield Sunglasses (Free Size)',
 'UV Protection, Gradient Butterfly, Retro Square Sunglas...',
 'UV Protection, Riding Glasses Aviator Sunglasses (58)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Retro Square Sunglasses (58)',
 'UV Protection, Mirrored Retro Square Sunglasses (Free S...',
 'Mirrored, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Aviator Sunglasses (54)',
 'Mirrored, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection, Polarized Rectangular Sunglasses (Free S...',
 'Mirrored Round Sunglasses (51)',
 'UV Protection, Mirrored Aviator Sunglasses (Free Size)',
 'Gradient, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Wayfarer Sunglasses (56)',
 'UV Protection Round Sunglasses (Free Size)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'Gradient, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection, Mirrored Retro Square Sunglasses (53)',
 'UV Protection Wrap-around Sunglasses (Free Size)',
 'UV Protection Butterfly Sunglasses (65)',
 'UV Protection, Riding Glasses Aviator Sunglasses (57)',
 'UV Protection, Gradient Round Sunglasses (Free Size)',
 'Polarized, UV Protection, Riding Glasses Wayfarer Sungl...',
 'UV Protection, Gradient Round Sunglasses (Free Size)',
 'Gradient, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Round Sunglasses (Free Size)',
 'UV Protection Retro Square Sunglasses (Free Size)',
 'UV Protection, Riding Glasses Wayfarer Sunglasses (53)',
 'UV Protection, Gradient Retro Square Sunglasses (Free S...',
 'UV Protection Sports Sunglasses (Free Size)',
 'Mirrored Wayfarer Sunglasses (55)',
 'UV Protection Oval Sunglasses (60)',
 'UV Protection, Night Vision, Riding Glasses Aviator Sun...',
 'UV Protection Round Sunglasses (Free Size)',
 'UV Protection, Riding Glasses Wayfarer Sunglasses (56)',
 'UV Protection, Mirrored Clubmaster Sunglasses (Free Siz...',
 'UV Protection, Riding Glasses Aviator Sunglasses (58)',
 'UV Protection Retro Square Sunglasses (Free Size)',
 'UV Protection, Mirrored Sports Sunglasses (73)',
 'UV Protection Shield Sunglasses (Free Size)',
 'UV Protection, Gradient Butterfly, Retro Square Sunglas...',
 'UV Protection, Riding Glasses Aviator Sunglasses (58)',
 'UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Retro Square Sunglasses (58)',
 'UV Protection, Mirrored Retro Square Sunglasses (Free S...',
 'Mirrored, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Aviator Sunglasses (54)',
 'Mirrored, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection, Polarized Rectangular Sunglasses (Free S...',
 'Mirrored Round Sunglasses (51)',
 'UV Protection, Mirrored Aviator Sunglasses (Free Size)',
 'Gradient, UV Protection Wayfarer Sunglasses (Free Size)',
 'UV Protection Wayfarer Sunglasses (56)',
 'UV Protection Round Sunglasses (Free Size)']

In [267]:
pro_price = []
for i in range(0,5):
    price = driver.find_elements_by_xpath('//div[@class="_30jeq3"]')
    for j in price:
        pro_price.append(j.text)
next_btn = driver.find_element_by_xpath('//a[@class="_1LKTO3"]')
next_btn.click()

In [268]:
pro_price

['â‚¹237',
 'â‚¹541',
 'â‚¹621',
 'â‚¹299',
 'â‚¹237',
 'â‚¹331',
 'â‚¹733',
 'â‚¹404',
 'â‚¹237',
 'â‚¹331',
 'â‚¹213',
 'â‚¹281',
 'â‚¹674',
 'â‚¹249',
 'â‚¹199',
 'â‚¹246',
 'â‚¹499',
 'â‚¹156',
 'â‚¹399',
 'â‚¹251',
 'â‚¹399',
 'â‚¹499',
 'â‚¹217',
 'â‚¹252',
 'â‚¹319',
 'â‚¹349',
 'â‚¹214',
 'â‚¹1,085',
 'â‚¹209',
 'â‚¹399',
 'â‚¹282',
 'â‚¹210',
 'â‚¹329',
 'â‚¹449',
 'â‚¹227',
 'â‚¹265',
 'â‚¹199',
 'â‚¹319',
 'â‚¹449',
 'â‚¹237',
 'â‚¹237',
 'â‚¹541',
 'â‚¹621',
 'â‚¹299',
 'â‚¹237',
 'â‚¹331',
 'â‚¹733',
 'â‚¹404',
 'â‚¹237',
 'â‚¹331',
 'â‚¹213',
 'â‚¹281',
 'â‚¹674',
 'â‚¹249',
 'â‚¹199',
 'â‚¹246',
 'â‚¹499',
 'â‚¹156',
 'â‚¹399',
 'â‚¹251',
 'â‚¹399',
 'â‚¹499',
 'â‚¹217',
 'â‚¹252',
 'â‚¹319',
 'â‚¹349',
 'â‚¹214',
 'â‚¹1,085',
 'â‚¹209',
 'â‚¹399',
 'â‚¹282',
 'â‚¹210',
 'â‚¹329',
 'â‚¹449',
 'â‚¹227',
 'â‚¹265',
 'â‚¹199',
 'â‚¹319',
 'â‚¹449',
 'â‚¹237',
 'â‚¹237',
 'â‚¹541',
 'â‚¹621',
 'â‚¹299',
 'â‚¹237',
 'â‚¹331',
 'â‚¹733',
 'â‚¹404',
 'â‚¹237',
 'â‚¹331',
 'â‚¹213',
 'â‚¹281',
 'â‚¹674',
 'â‚¹249',
 'â‚¹199',
 'â‚¹246',
 'â‚¹499',
 'â‚¹156',
 'â‚¹399',
 'â‚¹251',
 'â‚¹399',
 'â‚¹499',
 'â‚¹217',
 'â‚¹252',
 'â‚¹319',
 'â‚¹349',
 'â‚¹214',
 'â‚¹1,085',
 'â‚¹209',
 'â‚¹399',
 'â‚¹282',
 'â‚¹210',
 'â‚¹329',
 'â‚¹449',
 'â‚¹227',
 'â‚¹265',
 'â‚¹199',
 'â‚¹319',
 'â‚¹449',
 'â‚¹237',
 'â‚¹237',
 'â‚¹541',
 'â‚¹621',
 'â‚¹299',
 'â‚¹237',
 'â‚¹331',
 'â‚¹733',
 'â‚¹404',
 'â‚¹237',
 'â‚¹331',
 'â‚¹213',
 'â‚¹281',
 'â‚¹674',
 'â‚¹249',
 'â‚¹199',
 'â‚¹246',
 'â‚¹499',
 'â‚¹156',
 'â‚¹399',
 'â‚¹251',
 'â‚¹399',
 'â‚¹499',
 'â‚¹217',
 'â‚¹252',
 'â‚¹319',
 'â‚¹349',
 'â‚¹214',
 'â‚¹1,085',
 'â‚¹209',
 'â‚¹399',
 'â‚¹282',
 'â‚¹210',
 'â‚¹329',
 'â‚¹449',
 'â‚¹227',
 'â‚¹265',
 'â‚¹199',
 'â‚¹319',
 'â‚¹449',
 'â‚¹237',
 'â‚¹237',
 'â‚¹541',
 'â‚¹621',
 'â‚¹299',
 'â‚¹237',
 'â‚¹331',
 'â‚¹733',
 'â‚¹404',
 'â‚¹237',
 'â‚¹331',
 'â‚¹213',
 'â‚¹281',
 'â‚¹674',
 'â‚¹249',
 'â‚¹199',
 'â‚¹246',
 'â‚¹499',
 'â‚¹156',
 'â‚¹399',
 'â‚¹251',
 'â‚¹399',
 'â‚¹499',
 'â‚¹217',
 'â‚¹252',
 'â‚¹319',
 'â‚¹349',
 'â‚¹214',
 'â‚¹1,085',
 'â‚¹209',
 'â‚¹399',
 'â‚¹282',
 'â‚¹210',
 'â‚¹329',
 'â‚¹449',
 'â‚¹227',
 'â‚¹265',
 'â‚¹199',
 'â‚¹319',
 'â‚¹449',
 'â‚¹237']

In [269]:
pro_dis = []
for i in range(0,6):
    dis = driver.find_elements_by_xpath('//div[@class="_3Ay6Sb"]/span')
    for j in dis:
        pro_dis.append(j.text)
next_btn = driver.find_element_by_xpath('//a[@class="_1LKTO3"]')
next_btn.click()

In [270]:
pro_dis

['â‚¹141 off',
 'â‚¹337 off',
 'â‚¹161 off',
 'â‚¹1600 off',
 'â‚¹292 off',
 'â‚¹2276 off',
 'â‚¹1150 off',
 'â‚¹3214 off',
 'â‚¹350 off',
 'â‚¹1550 off',
 'â‚¹210 off',
 'â‚¹800 off',
 'â‚¹1210 off',
 'â‚¹1735 off',
 'â‚¹1550 off',
 'â‚¹1580 off',
 'â‚¹780 off',
 'â‚¹1711 off',
 'â‚¹1707 off',
 'â‚¹580 off',
 'â‚¹727 off',
 'â‚¹1679 off',
 'â‚¹1213 off',
 'â‚¹1800 off',
 'â‚¹878 off',
 'â‚¹140 off',
 'â‚¹951 off',
 'â‚¹839 off',
 'â‚¹252 off',
 'â‚¹1000 off',
 'â‚¹1600 off',
 'â‚¹2300 off',
 'â‚¹1362 off',
 'â‚¹222 off',
 'â‚¹1220 off',
 'â‚¹2264 off',
 'â‚¹800 off',
 'â‚¹112 off',
 'â‚¹140 off',
 'â‚¹1050 off',
 'â‚¹141 off',
 'â‚¹337 off',
 'â‚¹161 off',
 'â‚¹1600 off',
 'â‚¹292 off',
 'â‚¹2276 off',
 'â‚¹1150 off',
 'â‚¹3214 off',
 'â‚¹350 off',
 'â‚¹1550 off',
 'â‚¹210 off',
 'â‚¹800 off',
 'â‚¹1210 off',
 'â‚¹1735 off',
 'â‚¹1550 off',
 'â‚¹1580 off',
 'â‚¹780 off',
 'â‚¹1711 off',
 'â‚¹1707 off',
 'â‚¹580 off',
 'â‚¹727 off',
 'â‚¹1679 off',
 'â‚¹1213 off',
 'â‚¹1800 off',
 'â‚¹878 off',
 'â‚¹140 off',
 'â‚¹951 off',
 'â‚¹839 off',
 'â‚¹252 off',
 'â‚¹1000 off',
 'â‚¹1600 off',
 'â‚¹2300 off',
 'â‚¹1362 off',
 'â‚¹222 off',
 'â‚¹1220 off',
 'â‚¹2264 off',
 'â‚¹800 off',
 'â‚¹112 off',
 'â‚¹140 off',
 'â‚¹1050 off',
 'â‚¹141 off',
 'â‚¹337 off',
 'â‚¹161 off',
 'â‚¹1600 off',
 'â‚¹292 off',
 'â‚¹2276 off',
 'â‚¹1150 off',
 'â‚¹3214 off',
 'â‚¹350 off',
 'â‚¹1550 off',
 'â‚¹210 off',
 'â‚¹800 off',
 'â‚¹1210 off',
 'â‚¹1735 off',
 'â‚¹1550 off',
 'â‚¹1580 off',
 'â‚¹780 off',
 'â‚¹1711 off',
 'â‚¹1707 off',
 'â‚¹580 off',
 'â‚¹727 off',
 'â‚¹1679 off',
 'â‚¹1213 off',
 'â‚¹1800 off',
 'â‚¹878 off',
 'â‚¹140 off',
 'â‚¹951 off',
 'â‚¹839 off',
 'â‚¹252 off',
 'â‚¹1000 off',
 'â‚¹1600 off',
 'â‚¹2300 off',
 'â‚¹1362 off',
 'â‚¹222 off',
 'â‚¹1220 off',
 'â‚¹2264 off',
 'â‚¹800 off',
 'â‚¹112 off',
 'â‚¹140 off',
 'â‚¹1050 off',
 'â‚¹141 off',
 'â‚¹337 off',
 'â‚¹161 off',
 'â‚¹1600 off',
 'â‚¹292 off',
 'â‚¹2276 off',
 'â‚¹1150 off',
 'â‚¹3214 off',
 'â‚¹350 off',
 'â‚¹1550 off',
 'â‚¹210 off',
 'â‚¹800 off',
 'â‚¹1210 off',
 'â‚¹1735 off',
 'â‚¹1550 off',
 'â‚¹1580 off',
 'â‚¹780 off',
 'â‚¹1711 off',
 'â‚¹1707 off',
 'â‚¹580 off',
 'â‚¹727 off',
 'â‚¹1679 off',
 'â‚¹1213 off',
 'â‚¹1800 off',
 'â‚¹878 off',
 'â‚¹140 off',
 'â‚¹951 off',
 'â‚¹839 off',
 'â‚¹252 off',
 'â‚¹1000 off',
 'â‚¹1600 off',
 'â‚¹2300 off',
 'â‚¹1362 off',
 'â‚¹222 off',
 'â‚¹1220 off',
 'â‚¹2264 off',
 'â‚¹800 off',
 'â‚¹112 off',
 'â‚¹140 off',
 'â‚¹1050 off',
 'â‚¹141 off',
 'â‚¹337 off',
 'â‚¹161 off',
 'â‚¹1600 off',
 'â‚¹292 off',
 'â‚¹2276 off',
 'â‚¹1150 off',
 'â‚¹3214 off',
 'â‚¹350 off',
 'â‚¹1550 off',
 'â‚¹210 off',
 'â‚¹800 off',
 'â‚¹1210 off',
 'â‚¹1735 off',
 'â‚¹1550 off',
 'â‚¹1580 off',
 'â‚¹780 off',
 'â‚¹1711 off',
 'â‚¹1707 off',
 'â‚¹580 off',
 'â‚¹727 off',
 'â‚¹1679 off',
 'â‚¹1213 off',
 'â‚¹1800 off',
 'â‚¹878 off',
 'â‚¹140 off',
 'â‚¹951 off',
 'â‚¹839 off',
 'â‚¹252 off',
 'â‚¹1000 off',
 'â‚¹1600 off',
 'â‚¹2300 off',
 'â‚¹1362 off',
 'â‚¹222 off',
 'â‚¹1220 off',
 'â‚¹2264 off',
 'â‚¹800 off',
 'â‚¹112 off',
 'â‚¹140 off',
 'â‚¹1050 off',
 'â‚¹141 off',
 'â‚¹337 off',
 'â‚¹161 off',
 'â‚¹1600 off',
 'â‚¹292 off',
 'â‚¹2276 off',
 'â‚¹1150 off',
 'â‚¹3214 off',
 'â‚¹350 off',
 'â‚¹1550 off',
 'â‚¹210 off',
 'â‚¹800 off',
 'â‚¹1210 off',
 'â‚¹1735 off',
 'â‚¹1550 off',
 'â‚¹1580 off',
 'â‚¹780 off',
 'â‚¹1711 off',
 'â‚¹1707 off',
 'â‚¹580 off',
 'â‚¹727 off',
 'â‚¹1679 off',
 'â‚¹1213 off',
 'â‚¹1800 off',
 'â‚¹878 off',
 'â‚¹140 off',
 'â‚¹951 off',
 'â‚¹839 off',
 'â‚¹252 off',
 'â‚¹1000 off',
 'â‚¹1600 off',
 'â‚¹2300 off',
 'â‚¹1362 off',
 'â‚¹222 off',
 'â‚¹1220 off',
 'â‚¹2264 off',
 'â‚¹800 off',
 'â‚¹112 off',
 'â‚¹140 off',
 'â‚¹1050 off']

In [271]:
sunDis = pd.DataFrame({})
sunDis['Discounts'] = pro_dis

discounts = sunDis.iloc[0:200]
discounts

     Discounts
0     â‚¹141 off
1     â‚¹337 off
2     â‚¹161 off
3    â‚¹1600 off
4     â‚¹292 off
..         ...
195  â‚¹2264 off
196   â‚¹800 off
197   â‚¹112 off
198   â‚¹140 off
199  â‚¹1050 off

[200 rows x 1 columns]

In [272]:
sunglasses = pd.DataFrame({})
sunglasses['Brands'] = brands
sunglasses['Product Description'] = pro_desc
sunglasses['Price'] = pro_price
sunglasses['Dis'] = discounts
sunglasses.iloc[0:100]

,Brands,Product Description,Price,Dis
0,PIRASO,UV Protection Wayfarer Sunglasses (Free Size),â‚¹237,â‚¹141 off
1,Fastrack,UV Protection Wayfarer Sunglasses (Free Size),â‚¹541,â‚¹337 off
2,Fastrack,"Gradient, UV Protection Wayfarer Sunglasses (F...",â‚¹621,â‚¹161 off
3,kingsunglasses,"UV Protection, Mirrored Retro Square Sunglasse...",â‚¹299,â‚¹1600 off
4,PIRASO,UV Protection Wrap-around Sunglasses (Free Size),â‚¹237,â‚¹292 off
...,...,...,...,...
95,NuVew,UV Protection Sports Sunglasses (Free Size),â‚¹246,â‚¹1580 off
96,ROZZETTA CRAFT,Mirrored Wayfarer Sunglasses (55),â‚¹499,â‚¹780 off
97,Silver Kartz,UV Protection Oval Sunglasses (60),â‚¹156,â‚¹1711 off
98,PHENOMENAL,"UV Protection, Night Vision, Riding Glasses Av...",â‚¹399,â‚¹1707 off
99,HIPPON,UV Protection Round Sunglasses (Free Size),â‚¹251,â‚¹580 off

In [273]:
###Q7 ftech i phone data
url = 'https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/p/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace'
driver.get(url)

In [274]:
Review_scrap = driver.find_element_by_xpath('/html/body/div[1]/div/div[3]/div/div[2]/div[9]/div/div/div[5]/div/a')
Review_scrap.click()

In [275]:
review = []
for i in range(0,10):
    reviews = driver.find_elements_by_xpath('//div[@class="_3LWZlK _1BLPMq"]')
    for j in reviews:
        review.append(j.text)
next_btn = driver.find_element_by_xpath('/html/body/div[1]/div/div[3]/div/div/div[2]/div[13]/div/div/nav/a[11]').click()
review

['5',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '5',
 '4',
 '5',
 '5',
 '5',
 '5']

In [276]:
len(review)

100

In [277]:
review_sum = []
for i in range(0,10):
    reviews_sum = driver.find_elements_by_xpath('//p[@class="_2-N8zT"]')
    for j in reviews_sum:
        review_sum.append(j.text)
next_btn = driver.find_element_by_xpath('/html/body/div[1]/div/div[3]/div/div/div[2]/div[13]/div/div/nav/a[11]').click()
review_sum

['Perfect product!',
 'Highly recommended',
 'Simply awesome',
 'Worth every penny',
 'Nice product',
 'Terrific',
 'Classy product',
 'Highly recommended',
 'Wonderful',
 'Brilliant',
 'Perfect product!',
 'Highly recommended',
 'Simply awesome',
 'Worth every penny',
 'Nice product',
 'Terrific',
 'Classy product',
 'Highly recommended',
 'Wonderful',
 'Brilliant',
 'Perfect product!',
 'Highly recommended',
 'Simply awesome',
 'Worth every penny',
 'Nice product',
 'Terrific',
 'Classy product',
 'Highly recommended',
 'Wonderful',
 'Brilliant',
 'Perfect product!',
 'Highly recommended',
 'Simply awesome',
 'Worth every penny',
 'Nice product',
 'Terrific',
 'Classy product',
 'Highly recommended',
 'Wonderful',
 'Brilliant',
 'Perfect product!',
 'Highly recommended',
 'Simply awesome',
 'Worth every penny',
 'Nice product',
 'Terrific',
 'Classy product',
 'Highly recommended',
 'Wonderful',
 'Brilliant',
 'Perfect product!',
 'Highly recommended',
 'Simply awesome',
 'Worth every penny',
 'Nice product',
 'Terrific',
 'Classy product',
 'Highly recommended',
 'Wonderful',
 'Brilliant',
 'Perfect product!',
 'Highly recommended',
 'Simply awesome',
 'Worth every penny',
 'Nice product',
 'Terrific',
 'Classy product',
 'Highly recommended',
 'Wonderful',
 'Brilliant',
 'Perfect product!',
 'Highly recommended',
 'Simply awesome',
 'Worth every penny',
 'Nice product',
 'Terrific',
 'Classy product',
 'Highly recommended',
 'Wonderful',
 'Brilliant',
 'Perfect product!',
 'Highly recommended',
 'Simply awesome',
 'Worth every penny',
 'Nice product',
 'Terrific',
 'Classy product',
 'Highly recommended',
 'Wonderful',
 'Brilliant',
 'Perfect product!',
 'Highly recommended',
 'Simply awesome',
 'Worth every penny',
 'Nice product',
 'Terrific',
 'Classy product',
 'Highly recommended',
 'Wonderful',
 'Brilliant']

In [278]:
len(review_sum)

100

In [279]:
full_review = []
for i in range(0,10):
    reviews_ful = driver.find_elements_by_xpath('//div[@class="t-ZTKy"]')
    for j in reviews_ful:
        full_review.append(j.text)
next_btn = driver.find_element_by_xpath('/html/body/div[1]/div/div[3]/div/div/div[2]/div[13]/div/div/nav/a[11]').click()
full_review

["If you are looking for a premium phone under 55k, this is the one for you.Got the iPhone 11 during the Republic day sale. Performance is top notch in this price range. Camera's do a perfect job in taking good quality photos and videos. Battery backup too is satisfactory. Writing this review after using for a week. Any further observations would be updated.",
 'Awesome camera, smooth and fast UI, display is great (though not LED) but the black area at the top could have been reduced. Battery remains a day even if used heavily. Charger in the box is ok, but 12 or 18W could have been nothing like anything. Overall an excellent product and comfortable to use. I have got it almost a month back and so far so good.',
 "The best all rounder iphone. Flipkart is doing a great job. They're delivery services are blazing fast. I got delivery on the same day. Genuine Apple Product. Working great. Talking about review There's no need of review for iphones. They're simply the best.",
 'We are on apple ecosystem for almost eight years now with couple of iPads and iPhones, including Xr.\n\nBought iPhone 11 as a gift to my daughter who loves it. We chose for a purple coloured one. Believe me it is gorgeous and towards the lighter shade. Dazzling and brilliant!\n\nThe phone is great and does excellent RAM management like any other Apple device.\n\nThe screen, though a LCD and lesser ppi as compared to other flagship phones of competitor brands, is a delight to watch with perfect re...\nREAD MORE',
 'A perfect phone and a good battery super camera and the sound is dynamic overall the phone is perfect for upgrading from lower iPhone model to iPhone 11',
 "i was confused between 11 and 11 pro. i was going towards 11 pro, but the screen size was not enough for me.\nAnd i saw 11 in the showroom. i didn't find much difference in screen quality.And cameras seems to be ok with me. And i saw offer's in flipkart and made the purchase.\nthe device is fabulous. The hardware and software quality is excellent. The new iOS is something you need to experience yourself. The drawback i found was absence of fast charger, but the pricing can compensate that. Am...\nREAD MORE",
 'Product is nice at the deviled time the delivery boy not open the box and this order is oBD but he is not open and not showing product he gives Product and gone time God product is super nice and good Tq Flipkart and seller love you Flipkart Product is nice display good touch screen amazing compared to other brands over all Product is super. Tq Flipkart',
 "phone is good but in display is 720p lcd in this price range we can get full hd OLED displays with higher refresh rate processor is very good camera is nice but looks kind of oldish in front of todays phone also there's no charging in box had to buy it seperately",
 'Everything is perfect pictures come out so clearly and at first I wasnâ€™t sure when I got it then when I started to use it and get the hang of it it was amazing!! I canâ€™t wait to see what the next future phones will be like. The screen display on this bad boy are unbelievable they are so clear and never fail me. The performance is super cool there is a lot of cool features as well I like this phone because I feel that it is easy to use and one of my favorite things about this phone is the Face...\nREAD MORE',
 'I dreamt about this day from a long time.... Getting an iPhone with my own money.... Super happy and worth spending every penny',
 "If you are looking for a premium phone under 55k, this is the one for you.Got the iPhone 11 during the Republic day sale. Performance is top notch in this price range. Camera's do a perfect job in taking good quality photos and videos. Battery backup too is satisfactory. Writing this review after using for a week. Any further observations would be updated.",
 'Awesome camera, smooth and fast UI, display is great (though not LED) but the black area at the top could have been reduced. Battery remains a day even if used heavily. Charger in the box is ok, but 12 or 18W could have been nothing like anything. Overall an excellent product and comfortable to use. I have got it almost a month back and so far so good.',
 "The best all rounder iphone. Flipkart is doing a great job. They're delivery services are blazing fast. I got delivery on the same day. Genuine Apple Product. Working great. Talking about review There's no need of review for iphones. They're simply the best.",
 'We are on apple ecosystem for almost eight years now with couple of iPads and iPhones, including Xr.\n\nBought iPhone 11 as a gift to my daughter who loves it. We chose for a purple coloured one. Believe me it is gorgeous and towards the lighter shade. Dazzling and brilliant!\n\nThe phone is great and does excellent RAM management like any other Apple device.\n\nThe screen, though a LCD and lesser ppi as compared to other flagship phones of competitor brands, is a delight to watch with perfect re...\nREAD MORE',
 'A perfect phone and a good battery super camera and the sound is dynamic overall the phone is perfect for upgrading from lower iPhone model to iPhone 11',
 "i was confused between 11 and 11 pro. i was going towards 11 pro, but the screen size was not enough for me.\nAnd i saw 11 in the showroom. i didn't find much difference in screen quality.And cameras seems to be ok with me. And i saw offer's in flipkart and made the purchase.\nthe device is fabulous. The hardware and software quality is excellent. The new iOS is something you need to experience yourself. The drawback i found was absence of fast charger, but the pricing can compensate that. Am...\nREAD MORE",
 'Product is nice at the deviled time the delivery boy not open the box and this order is oBD but he is not open and not showing product he gives Product and gone time God product is super nice and good Tq Flipkart and seller love you Flipkart Product is nice display good touch screen amazing compared to other brands over all Product is super. Tq Flipkart',
 "phone is good but in display is 720p lcd in this price range we can get full hd OLED displays with higher refresh rate processor is very good camera is nice but looks kind of oldish in front of todays phone also there's no charging in box had to buy it seperately",
 'Everything is perfect pictures come out so clearly and at first I wasnâ€™t sure when I got it then when I started to use it and get the hang of it it was amazing!! I canâ€™t wait to see what the next future phones will be like. The screen display on this bad boy are unbelievable they are so clear and never fail me. The performance is super cool there is a lot of cool features as well I like this phone because I feel that it is easy to use and one of my favorite things about this phone is the Face...\nREAD MORE',
 'I dreamt about this day from a long time.... Getting an iPhone with my own money.... Super happy and worth spending every penny',
 "If you are looking for a premium phone under 55k, this is the one for you.Got the iPhone 11 during the Republic day sale. Performance is top notch in this price range. Camera's do a perfect job in taking good quality photos and videos. Battery backup too is satisfactory. Writing this review after using for a week. Any further observations would be updated.",
 'Awesome camera, smooth and fast UI, display is great (though not LED) but the black area at the top could have been reduced. Battery remains a day even if used heavily. Charger in the box is ok, but 12 or 18W could have been nothing like anything. Overall an excellent product and comfortable to use. I have got it almost a month back and so far so good.',
 "The best all rounder iphone. Flipkart is doing a great job. They're delivery services are blazing fast. I got delivery on the same day. Genuine Apple Product. Working great. Talking about review There's no need of review for iphones. They're simply the best.",
 'We are on apple ecosystem for almost eight years now with couple of iPads and iPhones, including Xr.\n\nBought iPhone 11 as a gift to my daughter who loves it. We chose for a purple coloured one. Believe me it is gorgeous and towards the lighter shade. Dazzling and brilliant!\n\nThe phone is great and does excellent RAM management like any other Apple device.\n\nThe screen, though a LCD and lesser ppi as compared to other flagship phones of competitor brands, is a delight to watch with perfect re...\nREAD MORE',
 'A perfect phone and a good battery super camera and the sound is dynamic overall the phone is perfect for upgrading from lower iPhone model to iPhone 11',
 "i was confused between 11 and 11 pro. i was going towards 11 pro, but the screen size was not enough for me.\nAnd i saw 11 in the showroom. i didn't find much difference in screen quality.And cameras seems to be ok with me. And i saw offer's in flipkart and made the purchase.\nthe device is fabulous. The hardware and software quality is excellent. The new iOS is something you need to experience yourself. The drawback i found was absence of fast charger, but the pricing can compensate that. Am...\nREAD MORE",
 'Product is nice at the deviled time the delivery boy not open the box and this order is oBD but he is not open and not showing product he gives Product and gone time God product is super nice and good Tq Flipkart and seller love you Flipkart Product is nice display good touch screen amazing compared to other brands over all Product is super. Tq Flipkart',
 "phone is good but in display is 720p lcd in this price range we can get full hd OLED displays with higher refresh rate processor is very good camera is nice but looks kind of oldish in front of todays phone also there's no charging in box had to buy it seperately",
 'Everything is perfect pictures come out so clearly and at first I wasnâ€™t sure when I got it then when I started to use it and get the hang of it it was amazing!! I canâ€™t wait to see what the next future phones will be like. The screen display on this bad boy are unbelievable they are so clear and never fail me. The performance is super cool there is a lot of cool features as well I like this phone because I feel that it is easy to use and one of my favorite things about this phone is the Face...\nREAD MORE',
 'I dreamt about this day from a long time.... Getting an iPhone with my own money.... Super happy and worth spending every penny',
 "If you are looking for a premium phone under 55k, this is the one for you.Got the iPhone 11 during the Republic day sale. Performance is top notch in this price range. Camera's do a perfect job in taking good quality photos and videos. Battery backup too is satisfactory. Writing this review after using for a week. Any further observations would be updated.",
 'Awesome camera, smooth and fast UI, display is great (though not LED) but the black area at the top could have been reduced. Battery remains a day even if used heavily. Charger in the box is ok, but 12 or 18W could have been nothing like anything. Overall an excellent product and comfortable to use. I have got it almost a month back and so far so good.',
 "The best all rounder iphone. Flipkart is doing a great job. They're delivery services are blazing fast. I got delivery on the same day. Genuine Apple Product. Working great. Talking about review There's no need of review for iphones. They're simply the best.",
 'We are on apple ecosystem for almost eight years now with couple of iPads and iPhones, including Xr.\n\nBought iPhone 11 as a gift to my daughter who loves it. We chose for a purple coloured one. Believe me it is gorgeous and towards the lighter shade. Dazzling and brilliant!\n\nThe phone is great and does excellent RAM management like any other Apple device.\n\nThe screen, though a LCD and lesser ppi as compared to other flagship phones of competitor brands, is a delight to watch with perfect re...\nREAD MORE',
 'A perfect phone and a good battery super camera and the sound is dynamic overall the phone is perfect for upgrading from lower iPhone model to iPhone 11',
 "i was confused between 11 and 11 pro. i was going towards 11 pro, but the screen size was not enough for me.\nAnd i saw 11 in the showroom. i didn't find much difference in screen quality.And cameras seems to be ok with me. And i saw offer's in flipkart and made the purchase.\nthe device is fabulous. The hardware and software quality is excellent. The new iOS is something you need to experience yourself. The drawback i found was absence of fast charger, but the pricing can compensate that. Am...\nREAD MORE",
 'Product is nice at the deviled time the delivery boy not open the box and this order is oBD but he is not open and not showing product he gives Product and gone time God product is super nice and good Tq Flipkart and seller love you Flipkart Product is nice display good touch screen amazing compared to other brands over all Product is super. Tq Flipkart',
 "phone is good but in display is 720p lcd in this price range we can get full hd OLED displays with higher refresh rate processor is very good camera is nice but looks kind of oldish in front of todays phone also there's no charging in box had to buy it seperately",
 'Everything is perfect pictures come out so clearly and at first I wasnâ€™t sure when I got it then when I started to use it and get the hang of it it was amazing!! I canâ€™t wait to see what the next future phones will be like. The screen display on this bad boy are unbelievable they are so clear and never fail me. The performance is super cool there is a lot of cool features as well I like this phone because I feel that it is easy to use and one of my favorite things about this phone is the Face...\nREAD MORE',
 'I dreamt about this day from a long time.... Getting an iPhone with my own money.... Super happy and worth spending every penny',
 "If you are looking for a premium phone under 55k, this is the one for you.Got the iPhone 11 during the Republic day sale. Performance is top notch in this price range. Camera's do a perfect job in taking good quality photos and videos. Battery backup too is satisfactory. Writing this review after using for a week. Any further observations would be updated.",
 'Awesome camera, smooth and fast UI, display is great (though not LED) but the black area at the top could have been reduced. Battery remains a day even if used heavily. Charger in the box is ok, but 12 or 18W could have been nothing like anything. Overall an excellent product and comfortable to use. I have got it almost a month back and so far so good.',
 "The best all rounder iphone. Flipkart is doing a great job. They're delivery services are blazing fast. I got delivery on the same day. Genuine Apple Product. Working great. Talking about review There's no need of review for iphones. They're simply the best.",
 'We are on apple ecosystem for almost eight years now with couple of iPads and iPhones, including Xr.\n\nBought iPhone 11 as a gift to my daughter who loves it. We chose for a purple coloured one. Believe me it is gorgeous and towards the lighter shade. Dazzling and brilliant!\n\nThe phone is great and does excellent RAM management like any other Apple device.\n\nThe screen, though a LCD and lesser ppi as compared to other flagship phones of competitor brands, is a delight to watch with perfect re...\nREAD MORE',
 'A perfect phone and a good battery super camera and the sound is dynamic overall the phone is perfect for upgrading from lower iPhone model to iPhone 11',
 "i was confused between 11 and 11 pro. i was going towards 11 pro, but the screen size was not enough for me.\nAnd i saw 11 in the showroom. i didn't find much difference in screen quality.And cameras seems to be ok with me. And i saw offer's in flipkart and made the purchase.\nthe device is fabulous. The hardware and software quality is excellent. The new iOS is something you need to experience yourself. The drawback i found was absence of fast charger, but the pricing can compensate that. Am...\nREAD MORE",
 'Product is nice at the deviled time the delivery boy not open the box and this order is oBD but he is not open and not showing product he gives Product and gone time God product is super nice and good Tq Flipkart and seller love you Flipkart Product is nice display good touch screen amazing compared to other brands over all Product is super. Tq Flipkart',
 "phone is good but in display is 720p lcd in this price range we can get full hd OLED displays with higher refresh rate processor is very good camera is nice but looks kind of oldish in front of todays phone also there's no charging in box had to buy it seperately",
 'Everything is perfect pictures come out so clearly and at first I wasnâ€™t sure when I got it then when I started to use it and get the hang of it it was amazing!! I canâ€™t wait to see what the next future phones will be like. The screen display on this bad boy are unbelievable they are so clear and never fail me. The performance is super cool there is a lot of cool features as well I like this phone because I feel that it is easy to use and one of my favorite things about this phone is the Face...\nREAD MORE',
 'I dreamt about this day from a long time.... Getting an iPhone with my own money.... Super happy and worth spending every penny',
 "If you are looking for a premium phone under 55k, this is the one for you.Got the iPhone 11 during the Republic day sale. Performance is top notch in this price range. Camera's do a perfect job in taking good quality photos and videos. Battery backup too is satisfactory. Writing this review after using for a week. Any further observations would be updated.",
 'Awesome camera, smooth and fast UI, display is great (though not LED) but the black area at the top could have been reduced. Battery remains a day even if used heavily. Charger in the box is ok, but 12 or 18W could have been nothing like anything. Overall an excellent product and comfortable to use. I have got it almost a month back and so far so good.',
 "The best all rounder iphone. Flipkart is doing a great job. They're delivery services are blazing fast. I got delivery on the same day. Genuine Apple Product. Working great. Talking about review There's no need of review for iphones. They're simply the best.",
 'We are on apple ecosystem for almost eight years now with couple of iPads and iPhones, including Xr.\n\nBought iPhone 11 as a gift to my daughter who loves it. We chose for a purple coloured one. Believe me it is gorgeous and towards the lighter shade. Dazzling and brilliant!\n\nThe phone is great and does excellent RAM management like any other Apple device.\n\nThe screen, though a LCD and lesser ppi as compared to other flagship phones of competitor brands, is a delight to watch with perfect re...\nREAD MORE',
 'A perfect phone and a good battery super camera and the sound is dynamic overall the phone is perfect for upgrading from lower iPhone model to iPhone 11',
 "i was confused between 11 and 11 pro. i was going towards 11 pro, but the screen size was not enough for me.\nAnd i saw 11 in the showroom. i didn't find much difference in screen quality.And cameras seems to be ok with me. And i saw offer's in flipkart and made the purchase.\nthe device is fabulous. The hardware and software quality is excellent. The new iOS is something you need to experience yourself. The drawback i found was absence of fast charger, but the pricing can compensate that. Am...\nREAD MORE",
 'Product is nice at the deviled time the delivery boy not open the box and this order is oBD but he is not open and not showing product he gives Product and gone time God product is super nice and good Tq Flipkart and seller love you Flipkart Product is nice display good touch screen amazing compared to other brands over all Product is super. Tq Flipkart',

In [280]:
len(full_review)

100

In [281]:
ReviewData = pd.DataFrame({})
ReviewData['Review'] = review
ReviewData['Review_Summary'] = review_sum
ReviewData['full_Review'] = full_review
ReviewData

,Review,Review_Summary,full_Review
0,5,Perfect product!,If you are looking for a premium phone under 5...
1,5,Highly recommended,"Awesome camera, smooth and fast UI, display is..."
2,5,Simply awesome,The best all rounder iphone. Flipkart is doing...
3,5,Worth every penny,We are on apple ecosystem for almost eight yea...
4,5,Nice product,A perfect phone and a good battery super camer...
...,...,...,...
95,4,Terrific,i was confused between 11 and 11 pro. i was go...
96,5,Classy product,Product is nice at the deviled time the delive...
97,5,Highly recommended,phone is good but in display is 720p lcd in th...
98,5,Wonderful,Everything is perfect pictures come out so cle...
99,5,Brilliant,I dreamt about this day from a long time.... G...

In [282]:

####Q8
url = 'https://www.flipkart.com/'
driver.get(url)

In [283]:
search = driver.find_element_by_xpath('//input[@class="_3704LK"]')
search.send_keys('sneakers')

In [287]:
Search_btn = driver.find_element_by_xpath('//button[@class="L0Z3Pu"]')
Search_btn.click()

In [288]:
brand = []
for i in range(0,3):
    brand_sneaker = driver.find_elements_by_xpath('//div[@class="_2WkVRV"]')
    for j in brand_sneaker:
        brand.append(j.text)
next_btn = driver.find_element_by_xpath('/html/body/div/div/div[3]/div[1]/div[2]/div[12]/div/div/nav/a[11]')
next_btn.click()
pd.DataFrame(brand).iloc[0:100]

               0
0         Chevit
1      India hub
2       CALCADOS
3     Shoes Bank
4   Robbie jones
..           ...
95    restinfoot
96      ASTEROID
97      HOTSTYLE
98        Chevit
99     SCATCHITE

[100 rows x 1 columns]

In [291]:
desc = []
for i in range(0,3):
    desc_sneaker = driver.find_elements_by_xpath('//a[@class="IRpwTa"]')
    for j in desc_sneaker:
        desc.append(j.text)
next_btn = driver.find_element_by_xpath('/html/body/div/div/div[3]/div[1]/div[2]/div[12]/div/div/nav/a[12]')
next_btn.click()

pd.DataFrame(desc).iloc[0:100]

                                                    0
0                        Smash v2 CV Sneakers For Men
1                                    Sneakers For Men
2               MAPM Future Kart Cat Sneakers For Men
3                                    Sneakers For Men
4                          Respin SL Sneakers For Men
..                                                ...
94  Combo Pack of 2 Latest Collection Stylish Casu...
95                                   Sneakers For Men
96               Men Combo Pack of 2 Sneakers For Men
97                       Rebound JOY Sneakers For Men
98                      Backcourt SL Sneakers For Men

[99 rows x 1 columns]

In [295]:
price = []
for i in range(0,3):
    p_sneaker = driver.find_elements_by_xpath('//div[@class="_30jeq3"]')
    for j in p_sneaker:
        price.append(j.text)
next_btn = driver.find_element_by_xpath('/html/body/div/div/div[3]/div[1]/div[2]/div[12]/div/div/nav/a[12]')
next_btn.click()

pd.DataFrame(price).iloc[0:100]

         0
0   â‚¹3,396
1   â‚¹1,282
2   â‚¹1,649
3   â‚¹1,642
4   â‚¹2,996
..     ...
95    â‚¹710
96    â‚¹599
97    â‚¹999
98    â‚¹630
99    â‚¹472

[100 rows x 1 columns]

In [296]:
dis = []
for i in range(0,3):
    dis_sneaker = driver.find_elements_by_xpath('//div[@class="_3Ay6Sb"]/span')
    for j in dis_sneaker:
        dis.append(j.text)
next_btn = driver.find_element_by_xpath('/html/body/div/div/div[3]/div[1]/div[2]/div[12]/div/div/nav/a[11]')
next_btn.click()

pd.DataFrame(dis).iloc[0:100]

            0
0    â‚¹535 off
1   â‚¹1581 off
2    â‚¹630 off
3   â‚¹1903 off
4    â‚¹448 off
..        ...
95   â‚¹299 off
96   â‚¹500 off
97   â‚¹233 off
98  â‚¹1900 off
99   â‚¹595 off

[100 rows x 1 columns]

In [309]:
### Q9
urlmyntra = 'https://www.myntra.com/shoes'
driver.get(urlmyntra)

In [310]:
driver.find_element_by_xpath('/html/body/div[2]/div/div[1]/main/div[3]/div[1]/section/div/div[6]/ul/li[1]/label').click()

In [313]:
driver.find_element_by_xpath('/html/body/div[2]/div/div[1]/main/div[3]/div[1]/section/div/div[5]/ul/li[2]/label').click()

In [314]:
brand = []
for i in range(0,2):
    brands = driver.find_elements_by_xpath('//h3[@class="product-brand"]')
    for j in brands:
        brand.append(j.text)
driver.find_element_by_xpath('/html/body/div[2]/div/div[1]/main/div[3]/div[2]/div/div[2]/section/div[2]/ul/li[12]/a').click()
brand

['Nike',
 'Nike',
 'Nike',
 'ASICS',
 'Nike',
 'Nike',
 'FORCLAZ By Decathlon',
 'Nike',
 'Nike',
 'Skechers',
 'Nike',
 'UNDER ARMOUR',
 'UNDER ARMOUR',
 'ADIDAS',
 'Tommy Hilfiger',
 'Hush Puppies',
 'Puma',
 'ASICS',
 'Puma',
 'Nike',
 'Puma',
 'UNDER ARMOUR',
 'Puma',
 'Nike',
 'UNDER ARMOUR',
 'ASICS',
 'ADIDAS Originals',
 'UNDER ARMOUR',
 'Puma',
 'Reebok',
 'UNDER ARMOUR',
 'Tommy Hilfiger',
 'Skechers',
 'UNDER ARMOUR',
 'ALDO',
 'FILA',
 'ALDO',
 'Ruosh',
 'RAPAWALK',
 'J.FONTINI',
 'UNDER ARMOUR',
 'ALDO',
 'Hush Puppies',
 'RAPAWALK',
 'Hush Puppies',
 'RAPAWALK',
 'RAPAWALK',
 'Heel & Buckle London',
 'Kalenji By Decathlon',
 'FILA',
 'Nike',
 'Nike',
 'Nike',
 'ASICS',
 'Nike',
 'Nike',
 'FORCLAZ By Decathlon',
 'Nike',
 'Nike',
 'Skechers',
 'Nike',
 'UNDER ARMOUR',
 'UNDER ARMOUR',
 'ADIDAS',
 'Tommy Hilfiger',
 'Hush Puppies',
 'Puma',
 'ASICS',
 'Puma',
 'Nike',
 'Puma',
 'UNDER ARMOUR',
 'Puma',
 'Nike',
 'UNDER ARMOUR',
 'ASICS',
 'ADIDAS Originals',
 'UNDER ARMOUR',
 'Puma',
 'Reebok',
 'UNDER ARMOUR',
 'Tommy Hilfiger',
 'Skechers',
 'UNDER ARMOUR',
 'ALDO',
 'FILA',
 'ALDO',
 'Ruosh',
 'RAPAWALK',
 'J.FONTINI',
 'UNDER ARMOUR',
 'ALDO',
 'Hush Puppies',
 'RAPAWALK',
 'Hush Puppies',
 'RAPAWALK',
 'RAPAWALK',
 'Heel & Buckle London',
 'Kalenji By Decathlon',
 'FILA']

In [317]:
len(brand)

100

In [318]:
desc_short = []
for i in range(0,2):
    desc = driver.find_elements_by_xpath('//h4[@class="product-product"]')
    for j in desc:
        desc_short.append(j.text)
driver.find_element_by_xpath('/html/body/div[2]/div/div[1]/main/div[3]/div[2]/div/div[2]/section/div[2]/ul/li[12]/a').click()
desc_short

['Women Peep Toe Heels',
 'Women Sneakers Casual Shoes',
 'Women Leather Sneakers',
 'Men Solid Leather Formal Loafers',
 'Women Running Shoes',
 'Men Textured Leather Loafers',
 'Wide Width Leather Slip Ons',
 'Wide Width Leather Slip Ons',
 'Men Liberate Nitro Running',
 'Women Edge Lux 4 Running',
 'Men Wingtip Oxford Sneakers',
 'Men GENERATION ZEROGRAND STITCHLITE',
 'Men Leather Sneakers',
 'Men Leather Sneakers',
 'Men IGNITE Dual Running Shoes',
 'Women Supernova+ Running',
 'Leather Sneakers',
 'Men Solid Sneakers',
 'Men Sneakers',
 'Men Leather Driving Shoes',
 'Men Textured Leather Monks',
 'Men JORDAN ONE TAKE II Shoes',
 'Men Zoom Winflo 8 Running',
 'Men ZOOM WINFLO8 Running Shoes',
 'Men Textured Sneakers',
 'Men AIR ZOOM PEGASUS 38 Run',
 'Men Textured Leather Loafers',
 'Men Leather Slip-On Sneakers',
 'Men Colourblocked Driving Shoes',
 'Men REACT MILER 2 Running',
 'Men REACT MILER 2 Running',
 'Charged Pursuit 2 Running',
 'Men ZOOM WINFLO 6 Running',
 'Women Solid Leather Gladiators',
 'Women Solid Leather Heels',
 'Men Woven Design Sneakers',
 'Men Woven Design Slip-On Sneakers',
 'Women Heeled Boots',
 'Men UltraRide Running Shoes',
 'Unisex Futurverse Sneakers',
 'Men Running Shoes',
 'Women Open Toe Flats',
 'Men Leather Loafers',
 'Women Solid Leather Ballerinas',
 'Women Sneakers',
 'Women Woven Design Sneakers',
 'Charged RC Sportstyle Sneakers',
 'Woven Design Casual Sneakers',
 'Liquify Rebel Running Shoes',
 'Women Leather Pumps',
 'Women Peep Toe Heels',
 'Women Sneakers Casual Shoes',
 'Women Leather Sneakers',
 'Men Solid Leather Formal Loafers',
 'Women Running Shoes',
 'Men Textured Leather Loafers',
 'Wide Width Leather Slip Ons',
 'Wide Width Leather Slip Ons',
 'Men Liberate Nitro Running',
 'Women Edge Lux 4 Running',
 'Men Wingtip Oxford Sneakers',
 'Men GENERATION ZEROGRAND STITCHLITE',
 'Men Leather Sneakers',
 'Men Leather Sneakers',
 'Men IGNITE Dual Running Shoes',
 'Women Supernova+ Running',
 'Leather Sneakers',
 'Men Solid Sneakers',
 'Men Sneakers',
 'Men Leather Driving Shoes',
 'Men Textured Leather Monks',
 'Men JORDAN ONE TAKE II Shoes',
 'Men Zoom Winflo 8 Running',
 'Men ZOOM WINFLO8 Running Shoes',
 'Men Textured Sneakers',
 'Men AIR ZOOM PEGASUS 38 Run',
 'Men Textured Leather Loafers',
 'Men Leather Slip-On Sneakers',
 'Men Colourblocked Driving Shoes',
 'Men REACT MILER 2 Running',
 'Men REACT MILER 2 Running',
 'Charged Pursuit 2 Running',
 'Men ZOOM WINFLO 6 Running',
 'Women Solid Leather Gladiators',
 'Women Solid Leather Heels',
 'Men Woven Design Sneakers',
 'Men Woven Design Slip-On Sneakers',
 'Women Heeled Boots',
 'Men UltraRide Running Shoes',
 'Unisex Futurverse Sneakers',
 'Men Running Shoes',
 'Women Open Toe Flats',
 'Men Leather Loafers',
 'Women Solid Leather Ballerinas',
 'Women Sneakers',
 'Women Woven Design Sneakers',
 'Charged RC Sportstyle Sneakers',
 'Woven Design Casual Sneakers',
 'Liquify Rebel Running Shoes',
 'Women Leather Pumps']

In [319]:
len(desc_short)

100

In [320]:
price = []
for i in range(0,4):
    p_shoes = driver.find_elements_by_xpath('//span[@class="product-discountedPrice"]')
    for j in p_shoes:
        price.append(j.text)
driver.find_element_by_xpath('/html/body/div[2]/div/div[1]/main/div[3]/div[2]/div/div[2]/section/div[2]/ul/li[12]/a').click()
price

['Rs. 8999',
 'Rs. 8799',
 'Rs. 7799',
 'Rs. 9793',
 'Rs. 9513',
 'Rs. 7192',
 'Rs. 8549',
 'Rs. 8399',
 'Rs. 9093',
 'Rs. 9796',
 'Rs. 9446',
 'Rs. 11596',
 'Rs. 12749',
 'Rs. 9599',
 'Rs. 9371',
 'Rs. 7699',
 'Rs. 9749',
 'Rs. 6799',
 'Rs. 10799',
 'Rs. 7992',
 'Rs. 7629',
 'Rs. 8999',
 'Rs. 8799',
 'Rs. 7799',
 'Rs. 9793',
 'Rs. 9513',
 'Rs. 7192',
 'Rs. 8549',
 'Rs. 8399',
 'Rs. 9093',
 'Rs. 9796',
 'Rs. 9446',
 'Rs. 11596',
 'Rs. 12749',
 'Rs. 9599',
 'Rs. 9371',
 'Rs. 7699',
 'Rs. 9749',
 'Rs. 6799',
 'Rs. 10799',
 'Rs. 7992',
 'Rs. 7629',
 'Rs. 8999',
 'Rs. 8799',
 'Rs. 7799',
 'Rs. 9793',
 'Rs. 9513',
 'Rs. 7192',
 'Rs. 8549',
 'Rs. 8399',
 'Rs. 9093',
 'Rs. 9796',
 'Rs. 9446',
 'Rs. 11596',
 'Rs. 12749',
 'Rs. 9599',
 'Rs. 9371',
 'Rs. 7699',
 'Rs. 9749',
 'Rs. 6799',
 'Rs. 10799',
 'Rs. 7992',
 'Rs. 7629',
 'Rs. 8999',
 'Rs. 8799',
 'Rs. 7799',
 'Rs. 9793',
 'Rs. 9513',
 'Rs. 7192',
 'Rs. 8549',
 'Rs. 8399',
 'Rs. 9093',
 'Rs. 9796',
 'Rs. 9446',
 'Rs. 11596',
 'Rs. 12749',
 'Rs. 9599',
 'Rs. 9371',
 'Rs. 7699',
 'Rs. 9749',
 'Rs. 6799',
 'Rs. 10799',
 'Rs. 7992',
 'Rs. 7629']

In [321]:
##### Q10 Scrap Data From Amazon
url = 'https://www.amazon.in/'
driver.get(url)

In [322]:
search_box = driver.find_element_by_xpath('//input[@id="twotabsearchtextbox"]')

In [323]:
search_box.send_keys('Laptop')

In [324]:
driver.find_element_by_xpath('//input[@id="nav-search-submit-button"]').click()

In [325]:
#check the checkbox for i9 and i7
driver.find_element_by_xpath('/html/body/div[1]/div[2]/div[1]/div/div[2]/div/div[3]/span/div[1]/span/div/div/div[5]/ul[1]/li[26]/span/a/div').click()

In [326]:
driver.find_element_by_xpath('/html/body/div[1]/div[2]/div[1]/div/div[2]/div/div[3]/span/div[1]/span/div/div/div[5]/ul[1]/li[28]/span/a/div').click()

In [327]:
title_data = driver.find_elements_by_xpath('//span[@class="a-size-medium a-color-base a-text-normal"]')
title_data

[<selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="ee1f3179-e105-4932-80a4-363f12f810fd")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="ca636151-3681-45a5-b0b4-1744d03629cd")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="06bf4fb7-4dcf-47aa-a197-528f2642865a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="9c7d46ee-4649-4eb1-a9ff-e7f58a291b60")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="96c63d68-65c1-4696-b269-2af3b983db4b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="cc90d84c-8279-4850-9723-f5ba4a06e21e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="31e5bb93-9522-4986-be66-72398af375c7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="1b920932-fadf-4d64-bbd8-97f3364b9734")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="44ea01c2-a54b-4f34-894d-fe4cd6d6324f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="4d71dd78-dd0a-4ba4-ae58-587835289326")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="107a6011-26bd-4167-9bd5-77afc5218fb7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="ffccf3d4-4eea-436b-b479-63ce71e636fd")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="d2474d24-9e4c-4103-9383-b89a1bee34ff")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="506a959d-3eea-4b07-896b-75765b1aa53e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="a1182f66-5578-4679-99d8-a645a1ab7894")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="da64e11e-e9e4-47da-9cab-649cb6c5d927")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="22cf8a7e-3549-4c7f-aff3-3ce88a6c67ba")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="b7c6a54c-cee0-474a-b00f-c7d2539fd4e5")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="1d5644b3-9ec2-4658-928a-abf9f33457e2")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="f5c8faa6-d995-4cd6-a1c8-5041c7c5bc66")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="516157a1-96f0-4ca9-801c-1f23fa1800c6")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="616253b5-1c26-46b0-8d66-889575d69faf")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="b07c000e-6af2-40da-a3e0-c3b5ce12ae7f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="af7736ff5ee88e3aee01364821fc3325", element="3cb12331-1269-4771-8aa1-040387c440ff")>]

In [328]:
### get the title for laptop
### blank list
title_lapppy = []
for i in title_data:
    title_lapppy.append(i.text)
title_lapppy

['HP Pavilion (2021) Thin & Light 11th Gen Core i7 Laptop, 16 GB RAM, 1TB SSD, Iris Xe Graphics, 14" (35.56cms) FHD Screen, Windows 10, MS Office, Backlit Keyboard (14-dv0058TU)',
 'Mi Notebook Horizon Edition 14 Intel Core i7-10510U 10th Gen 14-inch (35.56 cms) Thin and Light Laptop(8GB/512GB SSD/Windows 10/Nvidia MX350 2GB Graphics/Grey/1.35Kg), XMA1904-AF+Webcam',
 'Life Digital Laptop 15.6-inch (39.62 cms) (Intel Core i7, 4GB RAM, 256GB SSD, Windows 10), ZED AIR CX7',
 'HP Pavilion Gaming 10th Gen Intel Core i7 Processor 15.6-inch FHD Gaming Laptop (16GB/512GB SSD + 32GB Intel Optane/Windows 10/NVIDIA 1650Ti 4GB/Shadow Black), 15-dk1509TX',
 'Lenovo Ideapad 5 Intel i7 11th Gen 15.6" Thin and Light (16GB/512SSD/Win10 +Office Home/Intel Iris Xe Graphics/Graphite Grey/1.66kg), 82FG0117IN',
 '(Renewed) Dell XPS Intel 8th Gen Core i7 13.3-Inch (33.78 cms) 1920x1080 Thin and Light Laptop (16 GB/512 GB SSD/Windows 10/MS Office /Intel/Gold/1.21 Kg), 9370',
 'Lenovo IdeaPad Gaming 3 10th Gen Intel Core i7 15.6-inch FHD IPS Gaming Laptop (8GB/1TB HDD + 256 GB SSD/Windows 10/NVIDIA GTX 1650 4GB GDDR6/with M100 RGB Gaming Mouse/Onyx Black/2.2Kg), 81Y400VAIN',
 'Asus ZenBook UX330 UX330UA-FB088T 13.3-inch Laptop (Core i7-7500U/8GB/512GB/Windows 10/Integrated Graphics)',
 'HP Pavilion x360 (2021) 14" (35.56cms) FHD Touchscreen Laptop, 11th Gen Core i7, 8 GB RAM, 512GB SSD, 2-in-1 Convertible, Windows 10, MS Office, Finger Print Reader (14-dw1040TU)',
 'Lenovo IdeaPad Flex 5 11th Gen Intel Core i7 14-inch FHD IPS 2-in-1 Touchscreen Laptop (16GB/512GB SSD/Win 10/Office 2019/Lenovo Digital Pen Stylus/Fingerprint Reader/Graphite Grey/1.5Kg), 82HS0092IN',
 '(Renewed) Lenovo T430 14-inch Laptop (Core i7/ 16GB RAM/512GB SSD/Windows 10 Pro/MS Office 2019, Intel Integrated Graphics, PAN INDIA WARRANTY) Black',
 '(Renewed) Dell Latitude E7270 12.5 inch Laptop (Core i7 6th Gen/16 GB/256 GB SSD/Windows 10 Pro/MS Office/HD Display/Integrated Graphics)',
 'MSI GF63 Thin 10SCSR-019IN Intel Core i7-10750H 10th Gen 15.6-inch 120Hz Laptop(8GB/512GB NVMe SSD /Windows 10 Home/Nvidia GeForce GTX 1650Ti Max-Q 4GB/Black/1.8Kg ) 9S7-16R412-019',
 'ASUS ROG Zephyrus Duo 15, 15.6" 4K UHD, Intel Core i7-10875H 10th Gen, RTX 2080 Super Max-Q 8GB Graphics, Gaming Laptop (32GB/2TB RAID 0 SSD/Windows 10/MS Office/Gray/2.48 Kg) GX550LXS-HC145TS',
 'Dell Gaming-G3 3590 15.6-inch FHD Laptop (9th Gen Core i7-9750H/8GB/512GB SSD/Windows 10 + MS Office/4GB NVIDIA 1650 Graphics), Black',
 'Dell Inspiron 5406 14" FHD Touch Display 2in1 Laptop (11th Gen i7-1165G7 / 8Gb / 512Gb SSD / Integrated Graphics / Win 10 + MSO / Titan Grey Color / FPR/ Active Pen) D560414WIN9S',
 'HP 14 Thin & Light 14" (35.56cms) FHD Laptop (11th Gen Intel i7-1165G7/8GB/512GB SSD/Windows 10/MS Office 2019/Alexa Built-in/Pale Gold/1.47 kg), 14s-dr2007TU',
 '(Renewed) Lenovo T430 14-inch Laptop (Core i7/ 8GB RAM (Upgradable to 16)/1TB HDD/Windows 10 Pro/MS Office 2019, Intel Integrated Graphics, PAN INDIA WARRANTY) Black',
 '(Renewed) Dell Latitude E7270 12.5 inch Laptop (Core i7 6th Gen/8 GB (Up to 16)/256 GB SSD/Windows 10 Pro/MS Office/HD Display/Integrated Graphics)',
 'MSI GF63 Thin Core i7 9th Gen - (8 GB/512 GB SSD/Windows 10 Home/4 GB Graphics/NVIDIA Geforce GTX 1650 Ti with Max-Q) GF63 Thin 9SCSR-1039IN Gaming Laptop (15.6 inch, Black, 1.86 kg)',
 'Dell Inspiron 5410 14" FHD Touch Display 2in1 Laptop (i7-1165G7 / 16GB / 512GB SSD / Integrated Graphics / Win 10 + MSO / Backlit KB + FPR + Active Pen / Silver Metal Color) D560469WIN9S',
 '(Renewed) Dell Intel 6th Gen Core i7 6600U 14-Inch (35.56 cms) 1366x768 Laptop (8 GB/1 TB HDD/Windows 10/MS Office Pro 2019 /Intel HD Graphics 520/Black/1.26 Kg), Latitude E7470',
 'Lenovo Yoga 7 11th Gen Intel Core i7 14" (35.56cms) Full HD IPS 2-in-1 Touchscreen Laptop (16GB/512GB SSD/Windows 10/MS Office 2019/Fingerprint Reader/Slate Grey/Aluminium Surface/1.43Kg), 82BH004HIN',
 'Dell G3 3500 Gaming Laptop 15.6" (39.62cms) FHD 120 Hz (10th Gen Core i7-10750H/8GB/512GB SSD/Windows 10 Home Plus & MS Office/NVIDIA1650 Ti Graphics/Eclipse Black) D560260WIN9BE']

In [339]:
rating_lapppy = []
for i in range(0,10):
    rating = driver.find_elements_by_xpath('//span[@class="a-size-base"]')
    for i in rating:
        if i is None:
            continue
        else:
            rating_lapppy.append(i.text)
rating_lapppy

['100',
 '845',
 '8',
 '24',
 '4',
 '35',
 '6',
 '29',
 '26',
 '3',
 '7',
 '8',
 '10',
 '5',
 '8',
 '1',
 '12',
 '100',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '100',
 '845',
 '8',
 '24',
 '4',
 '35',
 '6',
 '29',
 '26',
 '3',
 '7',
 '8',
 '10',
 '5',
 '8',
 '1',
 '12',
 '100',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '100',
 '845',
 '8',
 '24',
 '4',
 '35',
 '6',
 '29',
 '26',
 '3',
 '7',
 '8',
 '10',
 '5',
 '8',
 '1',
 '12',
 '100',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '100',
 '845',
 '8',
 '24',
 '4',
 '35',
 '6',
 '29',
 '26',
 '3',
 '7',
 '8',
 '10',
 '5',
 '8',
 '1',
 '12',
 '100',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '100',
 '845',
 '8',
 '24',
 '4',
 '35',
 '6',
 '29',
 '26',
 '3',
 '7',
 '8',
 '10',
 '5',
 '8',
 '1',
 '12',
 '100',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '100',
 '845',
 '8',
 '24',
 '4',
 '35',
 '6',
 '29',
 '26',
 '3',
 '7',
 '8',
 '10',
 '5',
 '8',
 '1',
 '12',
 '100',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '100',
 '845',
 '8',
 '24',
 '4',
 '35',
 '6',
 '29',
 '26',
 '3',
 '7',
 '8',
 '10',
 '5',
 '8',
 '1',
 '12',
 '100',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '100',
 '845',
 '8',
 '24',
 '4',
 '35',
 '6',
 '29',
 '26',
 '3',
 '7',
 '8',
 '10',
 '5',
 '8',
 '1',
 '12',
 '100',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '100',
 '845',
 '8',
 '24',
 '4',
 '35',
 '6',
 '29',
 '26',
 '3',
 '7',
 '8',
 '10',
 '5',
 '8',
 '1',
 '12',
 '100',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '100',
 '845',
 '8',
 '24',
 '4',
 '35',
 '6',
 '29',
 '26',
 '3',
 '7',
 '8',
 '10',
 '5',
 '8',
 '1',
 '12',
 '100',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '',
 '']

In [341]:
lappy_price = []
for i in range(0,10):
    price = driver.find_elements_by_xpath('//span[@class="a-price-whole"]')
    for i in price:
        lappy_price.append(i.text)
pd.DataFrame(lappy_price).iloc[0:100]

         0
0   84,990
1   59,999
2   26,990
3   86,990
4   78,990
..     ...
95  96,000
96  78,990
97  90,400
98  61,899
99  89,990

[100 rows x 1 columns]

#### Glassdoor

In [157]:
###Q4 and 5
url='https://www.glassdoor.co.in/Salaries/index.htm'
driver.get(url)

In [158]:
#### sraech for data scientist
search = driver.find_element_by_xpath("//input[@id='KeywordSearch']")
search

In [159]:
search.send_keys('Data Scientist')

In [160]:
btn_search = driver.find_element_by_xpath("//button[@id='HeroSearchButton']")

In [161]:
btn_search.click()

In [174]:
###select Company Dropdown
driver.find_element_by_xpath("/html/body/header/nav[1]/div/div/div/div[3]/div[2]/form/div/div[2]/div/div[2]/div/ul/li[2]").click()

In [176]:
### filter Location Data
search_location = driver.find_element_by_xpath("//input[@id='sc.location']")

In [178]:
### clear location filled 
search_location.clear()

In [179]:
### send keys to search noida
search_location.send_keys('Noida')

In [180]:
### get The button path
seach_button = driver.find_element_by_xpath("//button[@class='gd-ui-button ml-std col-auto SearchStyles__newSearchButton css-iixdfr']")

In [181]:
#### click to search
seach_button.click()

In [182]:
Job_title = driver.find_elements_by_xpath("//div[@class='col-9 pr-0']")

In [185]:
title = []
for i in Job_title:
    title.append(i.text)
title

['dunnhumby\n4.1\nHammersmith, England, United Kingdom\nwww.dunnhumby.com',
 'IBM\n3.9\nArmonk, NY, United States\nwww.ibm.com',
 'Cognizant Technology Solutions\n3.8\nTeaneck, NJ, United States\nwww.cognizant.com',
 'UnitedHealth Group\n3.7\nMinnetonka, MN, United States\nwww.unitedhealthgroup.com',
 'Optum\n3.6\nEden Prairie, MN, United States\nwww.optum.com',
 'Accenture\n4.0\nDublin, Co. Dublin, Ireland\nwww.accenture.com',
 'Ericsson-Worldwide\n4.1\nStockholm, Stockholm, Sweden\nwww.ericsson.com',
 'Amazon\n4.3\nSeattle, WA, United States\nwww.amazon.jobs',
 'ZS Associates\n4.0\nEvanston, IL, United States\nwww.zs.com',
 'Fractal\n4.0\nNew York, NY, United States\nwww.fractal.ai']

In [186]:
pd.DataFrame(title)

                                                   0
0  dunnhumby\n4.1\nHammersmith, England, United K...
1   IBM\n3.9\nArmonk, NY, United States\nwww.ibm.com
2  Cognizant Technology Solutions\n3.8\nTeaneck, ...
3  UnitedHealth Group\n3.7\nMinnetonka, MN, Unite...
4  Optum\n3.6\nEden Prairie, MN, United States\nw...
5  Accenture\n4.0\nDublin, Co. Dublin, Ireland\nw...
6  Ericsson-Worldwide\n4.1\nStockholm, Stockholm,...
7  Amazon\n4.3\nSeattle, WA, United States\nwww.a...
8  ZS Associates\n4.0\nEvanston, IL, United State...
9  Fractal\n4.0\nNew York, NY, United States\nwww...

In [187]:
company = driver.find_elements_by_xpath('//span[@class="value"]')
company

[<selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="d9745e81-1232-41ce-bcc7-5d5df686fd92")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="7cd7ee13-f750-4226-b87a-7c528087d7fa")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="2d4d8e47-6371-4636-b256-0a20b52ad619")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="d20e6240-709e-4954-b251-9a9a2adfe709")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="ce5e2f31-caf7-42e4-a751-b316ed078871")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="c6bcfde9-85a4-42d5-ad81-eca2b2ea02a8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="c574114f-1ac4-4ec0-b59c-c27f4780ec91")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="fb89ed92-163c-4e9a-b978-1084155f632c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="ac3e1efb-16a6-44e4-a890-82c2dc376c2c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="0963c136-83ef-4bc6-bb46-8888b5d1cf3f")>]

In [188]:
company_data = []
for i in company:
    company_data.append(i.text)
company_data

['Hammersmith, England, United Kingdom',
 'Armonk, NY, United States',
 'Teaneck, NJ, United States',
 'Minnetonka, MN, United States',
 'Eden Prairie, MN, United States',
 'Dublin, Co. Dublin, Ireland',
 'Stockholm, Stockholm, Sweden',
 'Seattle, WA, United States',
 'Evanston, IL, United States',
 'New York, NY, United States']

In [190]:
salary =driver.find_elements_by_xpath('//span[@class="num h2"]')
salary

[<selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="be606ac4-8838-4bd7-bde1-e5bbf10683d2")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="8e9b9047-31b0-4539-abcc-4e0d877c5ef6")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="7f4642bf-d9d1-4bff-9f0d-014c1cc50508")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="aeef286d-cefc-4471-b556-2a449ed39fc0")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="f00cf2d3-2276-4431-8496-add131b93e9f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="26f7774d-cbb6-41cf-bf76-9843dac9da50")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="12563e87-32ed-4977-976a-47e197945712")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="17e0f255-882a-45bd-b173-8f3d17355762")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="88a117f1-28d0-4e3a-95e5-7963e3c0e966")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="0d589f22-ea03-4428-b4d9-7e6d22c56cfd")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="0c8aef45-883f-4bc1-a8ad-d25a87995af3")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="97581e0b-0a93-44b3-a24c-70de9a7be260")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="d91dd0b8-1074-4008-a659-c3196f6e09cf")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="b6f0ddbb-c1bc-4b7b-bb59-7d9458cea098")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="bd20f052-86b9-4a6c-9f2f-50d08312ab9d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="f2615648-cee2-41fd-8c90-9c2501601b3b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="e70d46b6-38ac-495f-84ec-5377b81491f8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="94cfd00f-93d2-48e4-922c-e9d95310836b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="f581de4e-b3f2-4233-87a9-12b10fa8a1d2")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="0bc5ffd6-419c-43b5-9f63-0cfb30b1d4a7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="5670cafc-1e51-463d-af6e-b9c7ec7675f6")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="43f3fad5-909b-41aa-ae44-6a7a8600de3d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="35b25868-f984-423f-9176-5d577d86ec6a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="dc2745a0-ad3d-4fe6-83d2-fe4c66da82c5")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="0a5f4362-4556-4e53-b314-c13b2864d69e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="26168159-ce53-4c3b-93d2-11f65f46148f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="c290b5ca-e800-4db2-8fb5-853a4319c116")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="0f384cbc-d432-4a1f-8d0a-3e361b9708a1")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="cc143d81-00dc-405e-ad81-de08bb7c5002")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="1984ce1a-17be-42ab-83ed-98d168084264")>]

In [191]:
salary_data = []
for i in salary:
    salary_data.append(i.text)
salary_data

['970',
 '1.2k',
 '212',
 '72k',
 '119k',
 '11k',
 '57k',
 '107k',
 '9.1k',
 '13k',
 '18k',
 '3.8k',
 '3.1k',
 '5.6k',
 '448',
 '88k',
 '120k',
 '18k',
 '14k',
 '16k',
 '2.0k',
 '82k',
 '146k',
 '32k',
 '4.0k',
 '6.6k',
 '1.9k',
 '914',
 '1.8k',
 '474']

In [195]:
salary=pd.DataFrame(salary_data)
salary

       0
0    970
1   1.2k
2    212
3    72k
4   119k
5    11k
6    57k
7   107k
8   9.1k
9    13k
10   18k
11  3.8k
12  3.1k
13  5.6k
14   448
15   88k
16  120k
17   18k
18   14k
19   16k
20  2.0k
21   82k
22  146k
23   32k
24  4.0k
25  6.6k
26  1.9k
27   914
28  1.8k
29   474

In [197]:
min_salary = salary.min()
min_salary

0    1.2k
dtype: object

In [198]:
max_salary = salary.max()
max_salary

0    970
dtype: object

In [192]:
rating = driver.find_elements_by_xpath('//span[@class="bigRating strong margRtSm h2"]')
rating

[<selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="916bc419-feb7-4243-b6b8-3af1564582d2")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="f312ec67-b4b0-40bd-9310-e8b861fdd7da")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="f229d380-9085-4ae6-90fd-0fd85d31a482")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="c681b9f6-d1ec-40f9-b6b0-8577037959ff")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="b0f28189-5601-4d4f-bf2d-fbf279e5a379")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="17dce1e7-9751-4182-b6fd-987f3c2e64e3")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="0758cf7e-9364-462d-8298-6905fed9ca60")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="e7c7e450-d8ce-4288-acfb-7209cd82ce24")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="4f132d8d-a3fa-4a6a-a80b-3144ed347345")>,
 <selenium.webdriver.remote.webelement.WebElement (session="1e78846b6da692552535023352da6a79", element="b4686016-cc85-45cc-9b4f-893c24223ca4")>]

In [193]:
rating_data = []
for i in rating:
    rating_data.append(i.text)
rating_data

['4.1', '3.9', '3.8', '3.7', '3.6', '4.0', '4.1', '4.3', '4.0', '4.0']